/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.skd.nautilusapi.client.model.Animations.ModelAnimator
 *  com.skd.nautilusapi.client.model.tools.AdvancedEntityModel
 *  com.skd.nautilusapi.client.model.tools.AdvancedModelBox
 *  com.skd.nautilusapi.client.model.tools.BasicModelPart
 *  com.skd.nautilusapi.server.animation.IAnimatedEntity
 *  com.google.common.collect.ImmutableList
 *  net.minecraft.client.Minecraft
 */
package com.skd.cataclysmbosses.client.model.entity;

import com.skd.cataclysmbosses.entity.Pet.The_Baby_Leviathan_Entity;
import com.skd.nautilusapi.client.model.Animations.ModelAnimator;
import com.skd.nautilusapi.client.model.tools.AdvancedEntityModel;
import com.skd.nautilusapi.client.model.tools.AdvancedModelBox;
import com.skd.nautilusapi.client.model.tools.BasicModelPart;
import com.skd.nautilusapi.server.animation.IAnimatedEntity;
import com.google.common.collect.ImmutableList;
import net.minecraft.client.Minecraft;

public class The_Baby_Leviathan_Model
extends AdvancedEntityModel<The_Baby_Leviathan_Entity> {
    private final AdvancedModelBox root;
    private final AdvancedModelBox body;
    private final AdvancedModelBox main_belly;
    private final AdvancedModelBox r_tentacle;
    private final AdvancedModelBox r_tentacle2;
    private final AdvancedModelBox r_hook1;
    private final AdvancedModelBox r_hook4;
    private final AdvancedModelBox r_hook2;
    private final AdvancedModelBox r_hook3;
    private final AdvancedModelBox l_tentacle;
    private final AdvancedModelBox l_tentacle2;
    private final AdvancedModelBox l_hook1;
    private final AdvancedModelBox l_hook2;
    private final AdvancedModelBox l_hook3;
    private final AdvancedModelBox l_hook4;
    private final AdvancedModelBox belly;
    private final AdvancedModelBox r_down_fin;
    private final AdvancedModelBox l_down_fin;
    private final AdvancedModelBox tail;
    private final AdvancedModelBox tail_back;
    private final AdvancedModelBox r_spike2;
    private final AdvancedModelBox l_spike2;
    private final AdvancedModelBox head;
    private final AdvancedModelBox maw;
    private final AdvancedModelBox skul;
    private final AdvancedModelBox main_mouth;
    private final AdvancedModelBox mouth1;
    private final AdvancedModelBox mouth1_e;
    private final AdvancedModelBox mouth2;
    private final AdvancedModelBox mouth2_e;
    private final AdvancedModelBox mouth3;
    private final AdvancedModelBox mouth3_e;
    private final AdvancedModelBox mouth4;
    private final AdvancedModelBox mouth4_e;
    private final AdvancedModelBox r_fin;
    private final AdvancedModelBox l_fin;
    private final AdvancedModelBox r_spike1;
    private final AdvancedModelBox l_spike1;
    private ModelAnimator animator;

    public The_Baby_Leviathan_Model() {
        this.texWidth = 64;
        this.texHeight = 64;
        this.root = new AdvancedModelBox((AdvancedEntityModel)this);
        this.root.setRotationPoint(0.0f, 24.0f, 0.0f);
        this.head = new AdvancedModelBox((AdvancedEntityModel)this);
        this.head.setRotationPoint(0.0f, -2.4f, -5.9f);
        this.root.addChild((BasicModelPart)this.head);
        this.maw = new AdvancedModelBox((AdvancedEntityModel)this);
        this.maw.setRotationPoint(0.0f, 0.75f, 0.0f);
        this.head.addChild((BasicModelPart)this.maw);
        this.maw.setTextureOffset(34, 20).addBox(-1.5f, -1.15f, -3.1f, 3.0f, 2.0f, 3.0f, 0.0f, false);
        this.maw.setTextureOffset(10, 0).addBox(-1.5f, -0.15f, -3.1f, 3.0f, 0.0f, 3.0f, 0.0f, false);
        this.maw.setTextureOffset(10, 4).addBox(-1.0f, -1.05f, -3.9f, 2.0f, 2.0f, 1.0f, 0.0f, false);
        this.maw.setTextureOffset(0, 7).addBox(-1.0f, -0.05f, -3.9f, 2.0f, 0.0f, 1.0f, 0.0f, false);
        this.skul = new AdvancedModelBox((AdvancedEntityModel)this);
        this.skul.setRotationPoint(0.0f, -1.1f, -0.1f);
        this.head.addChild((BasicModelPart)this.skul);
        this.skul.setTextureOffset(6, 28).addBox(-1.0f, -1.0f, -3.8f, 2.0f, 2.0f, 1.0f, -0.1f, false);
        this.skul.setTextureOffset(34, 26).addBox(-1.5f, -1.0f, -3.0f, 3.0f, 2.0f, 3.0f, -0.1f, false);
        this.main_mouth = new AdvancedModelBox((AdvancedEntityModel)this);
        this.main_mouth.setRotationPoint(0.0f, -0.1f, -0.1f);
        this.head.addChild((BasicModelPart)this.main_mouth);
        this.mouth1 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.mouth1.setRotationPoint(-1.5f, 0.9064f, 0.0717f);
        this.main_mouth.addChild((BasicModelPart)this.mouth1);
        this.setRotationAngle(this.mouth1, 0.0f, 0.0f, 0.0f);
        this.mouth1.setTextureOffset(11, 31).addBox(-1.5f, -0.9064f, -3.0717f, 3.0f, 2.0f, 3.0f, 0.0f, false);
        this.mouth1_e = new AdvancedModelBox((AdvancedEntityModel)this);
        this.mouth1_e.setRotationPoint(0.0f, 1.0936f, -3.0717f);
        this.mouth1.addChild((BasicModelPart)this.mouth1_e);
        this.setRotationAngle(this.mouth1_e, -0.0873f, 0.0f, 0.0f);
        this.mouth1_e.setTextureOffset(0, 17).addBox(-1.51f, -2.01f, -3.01f, 3.0f, 2.0f, 3.0f, 0.01f, false);
        this.mouth2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.mouth2.setRotationPoint(1.5f, 0.9064f, 0.0717f);
        this.main_mouth.addChild((BasicModelPart)this.mouth2);
        this.setRotationAngle(this.mouth2, 0.0f, 0.0f, 0.0f);
        this.mouth2.setTextureOffset(11, 31).addBox(-1.5f, -0.9064f, -3.0717f, 3.0f, 2.0f, 3.0f, 0.0f, true);
        this.mouth2_e = new AdvancedModelBox((AdvancedEntityModel)this);
        this.mouth2_e.setRotationPoint(0.0f, 1.0936f, -3.0717f);
        this.mouth2.addChild((BasicModelPart)this.mouth2_e);
        this.setRotationAngle(this.mouth2_e, -0.0873f, 0.0f, 0.0f);
        this.mouth2_e.setTextureOffset(0, 17).addBox(-1.49f, -2.01f, -3.01f, 3.0f, 2.0f, 3.0f, 0.01f, true);
        this.mouth3 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.mouth3.setRotationPoint(-1.5f, -0.9064f, 0.0717f);
        this.main_mouth.addChild((BasicModelPart)this.mouth3);
        this.mouth3.setTextureOffset(32, 10).addBox(-1.5f, -1.0936f, -3.0717f, 3.0f, 2.0f, 3.0f, 0.0f, false);
        this.mouth3_e = new AdvancedModelBox((AdvancedEntityModel)this);
        this.mouth3_e.setRotationPoint(0.0f, -1.0936f, -3.0717f);
        this.mouth3.addChild((BasicModelPart)this.mouth3_e);
        this.setRotationAngle(this.mouth3_e, 0.0873f, 0.0f, 0.0f);
        this.mouth3_e.setTextureOffset(24, 31).addBox(-1.515f, 0.015f, -3.015f, 3.0f, 2.0f, 3.0f, 0.015f, false);
        this.mouth4 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.mouth4.setRotationPoint(1.5f, -0.9064f, 0.0717f);
        this.main_mouth.addChild((BasicModelPart)this.mouth4);
        this.mouth4.setTextureOffset(32, 10).addBox(-1.5f, -1.0936f, -3.0717f, 3.0f, 2.0f, 3.0f, 0.0f, true);
        this.mouth4_e = new AdvancedModelBox((AdvancedEntityModel)this);
        this.mouth4_e.setRotationPoint(0.0f, -1.0936f, -3.0717f);
        this.mouth4.addChild((BasicModelPart)this.mouth4_e);
        this.setRotationAngle(this.mouth4_e, 0.0873f, 0.0f, 0.0f);
        this.mouth4_e.setTextureOffset(24, 31).addBox(-1.485f, 0.015f, -3.015f, 3.0f, 2.0f, 3.0f, 0.015f, true);
        this.body = new AdvancedModelBox((AdvancedEntityModel)this);
        this.body.setRotationPoint(0.0f, 0.4f, 8.8f);
        this.head.addChild((BasicModelPart)this.body);
        this.body.setTextureOffset(14, 12).addBox(-3.0f, -3.0f, -8.9f, 6.0f, 5.0f, 5.0f, 0.0f, false);
        this.body.setTextureOffset(0, 28).addBox(0.0f, -6.0f, -8.9f, 0.0f, 3.0f, 5.0f, 0.0f, false);
        this.main_belly = new AdvancedModelBox((AdvancedEntityModel)this);
        this.main_belly.setRotationPoint(-0.9512f, 0.0f, -3.9f);
        this.body.addChild((BasicModelPart)this.main_belly);
        this.main_belly.setTextureOffset(19, 0).addBox(-1.5488f, -3.0f, 0.0f, 5.0f, 5.0f, 4.0f, 0.0f, false);
        this.main_belly.setTextureOffset(0, 0).addBox(0.9512f, -5.0f, 0.0f, 0.0f, 2.0f, 4.0f, 0.0f, false);
        this.r_tentacle = new AdvancedModelBox((AdvancedEntityModel)this);
        this.r_tentacle.setRotationPoint(-1.5488f, -1.5f, 2.5f);
        this.main_belly.addChild((BasicModelPart)this.r_tentacle);
        this.setRotationAngle(this.r_tentacle, 0.0f, -0.6109f, 0.0f);
        this.r_tentacle.setTextureOffset(36, 36).addBox(-6.0f, -0.5f, -0.5f, 6.0f, 1.0f, 1.0f, 0.0f, false);
        this.r_tentacle2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.r_tentacle2.setRotationPoint(-6.0f, 0.0f, 0.0f);
        this.r_tentacle.addChild((BasicModelPart)this.r_tentacle2);
        this.setRotationAngle(this.r_tentacle2, 0.0f, -0.9599f, 0.0f);
        this.r_tentacle2.setTextureOffset(34, 0).addBox(-6.0f, -0.5f, -0.5f, 6.0f, 1.0f, 1.0f, 0.0f, false);
        this.r_hook1 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.r_hook1.setRotationPoint(-6.0f, 0.0f, 0.5f);
        this.r_tentacle2.addChild((BasicModelPart)this.r_hook1);
        this.setRotationAngle(this.r_hook1, 0.0f, 0.7854f, 0.0f);
        this.r_hook1.setTextureOffset(0, 0).addBox(-1.0f, -0.5f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, false);
        this.r_hook4 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.r_hook4.setRotationPoint(-6.0f, 0.0f, -0.5f);
        this.r_tentacle2.addChild((BasicModelPart)this.r_hook4);
        this.setRotationAngle(this.r_hook4, 0.0f, -0.7854f, 0.0f);
        this.r_hook4.setTextureOffset(0, 0).addBox(-1.0f, -0.5f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, false);
        this.r_hook2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.r_hook2.setRotationPoint(-6.0f, -0.5f, 0.0f);
        this.r_tentacle2.addChild((BasicModelPart)this.r_hook2);
        this.setRotationAngle(this.r_hook2, 0.0f, 0.0f, 0.7854f);
        this.r_hook2.setTextureOffset(19, 10).addBox(-1.0f, 0.0f, -0.5f, 1.0f, 0.0f, 1.0f, 0.0f, false);
        this.r_hook3 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.r_hook3.setRotationPoint(-6.0f, 0.5f, 0.0f);
        this.r_tentacle2.addChild((BasicModelPart)this.r_hook3);
        this.setRotationAngle(this.r_hook3, 0.0f, 0.0f, -0.7854f);
        this.r_hook3.setTextureOffset(19, 10).addBox(-1.0f, 0.0f, -0.5f, 1.0f, 0.0f, 1.0f, 0.0f, false);
        this.l_tentacle = new AdvancedModelBox((AdvancedEntityModel)this);
        this.l_tentacle.setRotationPoint(3.4512f, -1.5f, 2.5f);
        this.main_belly.addChild((BasicModelPart)this.l_tentacle);
        this.setRotationAngle(this.l_tentacle, 0.0f, 0.6109f, 0.0f);
        this.l_tentacle.setTextureOffset(36, 36).addBox(0.0f, -0.5f, -0.5f, 6.0f, 1.0f, 1.0f, 0.0f, true);
        this.l_tentacle2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.l_tentacle2.setRotationPoint(6.0f, 0.0f, 0.0f);
        this.l_tentacle.addChild((BasicModelPart)this.l_tentacle2);
        this.setRotationAngle(this.l_tentacle2, 0.0f, 0.9599f, 0.0f);
        this.l_tentacle2.setTextureOffset(34, 0).addBox(0.0f, -0.5f, -0.5f, 6.0f, 1.0f, 1.0f, 0.0f, true);
        this.l_hook1 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.l_hook1.setRotationPoint(6.0f, 0.0f, 0.5f);
        this.l_tentacle2.addChild((BasicModelPart)this.l_hook1);
        this.setRotationAngle(this.l_hook1, 0.0f, -0.7854f, 0.0f);
        this.l_hook1.setTextureOffset(0, 0).addBox(0.0f, -0.5f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, true);
        this.l_hook2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.l_hook2.setRotationPoint(6.0f, 0.0f, -0.5f);
        this.l_tentacle2.addChild((BasicModelPart)this.l_hook2);
        this.setRotationAngle(this.l_hook2, 0.0f, 0.7854f, 0.0f);
        this.l_hook2.setTextureOffset(0, 0).addBox(0.0f, -0.5f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, true);
        this.l_hook3 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.l_hook3.setRotationPoint(6.0f, -0.5f, 0.0f);
        this.l_tentacle2.addChild((BasicModelPart)this.l_hook3);
        this.setRotationAngle(this.l_hook3, 0.0f, 0.0f, -0.7854f);
        this.l_hook3.setTextureOffset(19, 10).addBox(0.0f, 0.0f, -0.5f, 1.0f, 0.0f, 1.0f, 0.0f, true);
        this.l_hook4 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.l_hook4.setRotationPoint(6.0f, 0.5f, 0.0f);
        this.l_tentacle2.addChild((BasicModelPart)this.l_hook4);
        this.setRotationAngle(this.l_hook4, 0.0f, 0.0f, 0.7854f);
        this.l_hook4.setTextureOffset(19, 10).addBox(0.0f, 0.0f, -0.5f, 1.0f, 0.0f, 1.0f, 0.0f, true);
        this.belly = new AdvancedModelBox((AdvancedEntityModel)this);
        this.belly.setRotationPoint(0.9512f, -1.0f, 4.0f);
        this.main_belly.addChild((BasicModelPart)this.belly);
        this.belly.setTextureOffset(19, 23).addBox(-2.0f, -2.0f, 0.0f, 4.0f, 4.0f, 3.0f, 0.0f, false);
        this.belly.setTextureOffset(42, 42).addBox(0.0f, -4.0f, 0.0f, 0.0f, 2.0f, 3.0f, 0.0f, false);
        this.r_down_fin = new AdvancedModelBox((AdvancedEntityModel)this);
        this.r_down_fin.setRotationPoint(-2.0f, 2.0f, 1.0f);
        this.belly.addChild((BasicModelPart)this.r_down_fin);
        this.setRotationAngle(this.r_down_fin, 0.0f, 0.0f, -0.5236f);
        this.r_down_fin.setTextureOffset(37, 16).addBox(-2.0f, 0.0f, -1.0f, 2.0f, 0.0f, 3.0f, 0.0f, false);
        this.l_down_fin = new AdvancedModelBox((AdvancedEntityModel)this);
        this.l_down_fin.setRotationPoint(2.0f, 2.0f, 1.0f);
        this.belly.addChild((BasicModelPart)this.l_down_fin);
        this.setRotationAngle(this.l_down_fin, 0.0f, 0.0f, 0.5236f);
        this.l_down_fin.setTextureOffset(37, 16).addBox(0.0f, 0.0f, -1.0f, 2.0f, 0.0f, 3.0f, 0.0f, true);
        this.tail = new AdvancedModelBox((AdvancedEntityModel)this);
        this.tail.setRotationPoint(0.0f, -0.5f, 3.0f);
        this.belly.addChild((BasicModelPart)this.tail);
        this.tail.setTextureOffset(11, 37).addBox(-1.0f, -1.5f, 0.0f, 2.0f, 3.0f, 3.0f, 0.0f, false);
        this.tail.setTextureOffset(38, 39).addBox(0.0f, -3.5f, 0.0f, 0.0f, 2.0f, 3.0f, 0.0f, false);
        this.tail.setTextureOffset(31, 37).addBox(0.0f, 1.5f, 0.0f, 0.0f, 2.0f, 3.0f, 0.0f, false);
        this.tail_back = new AdvancedModelBox((AdvancedEntityModel)this);
        this.tail_back.setRotationPoint(0.0f, -0.25f, 3.0f);
        this.tail.addChild((BasicModelPart)this.tail_back);
        this.tail_back.setTextureOffset(38, 3).addBox(-0.5f, -1.25f, 0.0f, 1.0f, 2.0f, 3.0f, 0.0f, false);
        this.tail_back.setTextureOffset(0, 0).addBox(0.0f, -3.25f, 0.0f, 0.0f, 7.0f, 9.0f, 0.0f, false);
        this.r_spike2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.r_spike2.setRotationPoint(-1.5488f, -3.0f, 2.0f);
        this.main_belly.addChild((BasicModelPart)this.r_spike2);
        this.setRotationAngle(this.r_spike2, 0.0f, 0.0f, -0.7854f);
        this.r_spike2.setTextureOffset(22, 37).addBox(0.0f, -1.0f, -2.0f, 0.0f, 1.0f, 4.0f, 0.0f, false);
        this.l_spike2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.l_spike2.setRotationPoint(3.4512f, -3.0f, 2.0f);
        this.main_belly.addChild((BasicModelPart)this.l_spike2);
        this.setRotationAngle(this.l_spike2, 0.0f, 0.0f, 0.7854f);
        this.l_spike2.setTextureOffset(22, 37).addBox(0.0f, -1.0f, -2.0f, 0.0f, 1.0f, 4.0f, 0.0f, true);
        this.r_fin = new AdvancedModelBox((AdvancedEntityModel)this);
        this.r_fin.setRotationPoint(-3.0f, 1.75f, -6.9f);
        this.body.addChild((BasicModelPart)this.r_fin);
        this.setRotationAngle(this.r_fin, 0.0f, 0.0f, -0.0436f);
        this.r_fin.setTextureOffset(0, 23).addBox(-5.0f, 0.0f, -2.0f, 5.0f, 0.0f, 4.0f, 0.0f, false);
        this.l_fin = new AdvancedModelBox((AdvancedEntityModel)this);
        this.l_fin.setRotationPoint(3.0f, 1.75f, -6.9f);
        this.body.addChild((BasicModelPart)this.l_fin);
        this.setRotationAngle(this.l_fin, 0.0f, 0.0f, 0.0436f);
        this.l_fin.setTextureOffset(0, 23).addBox(0.0f, 0.0f, -2.0f, 5.0f, 0.0f, 4.0f, 0.0f, true);
        this.r_spike1 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.r_spike1.setRotationPoint(-3.0f, -3.0f, -6.4f);
        this.body.addChild((BasicModelPart)this.r_spike1);
        this.setRotationAngle(this.r_spike1, 0.0f, 0.0f, -0.7854f);
        this.r_spike1.setTextureOffset(0, 37).addBox(0.0f, -1.0f, -2.5f, 0.0f, 1.0f, 5.0f, 0.0f, false);
        this.l_spike1 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.l_spike1.setRotationPoint(3.0f, -3.0f, -6.4f);
        this.body.addChild((BasicModelPart)this.l_spike1);
        this.setRotationAngle(this.l_spike1, 0.0f, 0.0f, 0.7854f);
        this.l_spike1.setTextureOffset(0, 37).addBox(0.0f, -1.0f, -2.5f, 0.0f, 1.0f, 5.0f, 0.0f, true);
        this.animator = ModelAnimator.create();
        this.updateDefaultPose();
    }

    public void animate(The_Baby_Leviathan_Entity entity, float f, float f1, float f2, float f3, float f4) {
        this.resetToDefaultPose();
        this.animator.update((IAnimatedEntity)entity);
        this.animator.setAnimation(The_Baby_Leviathan_Entity.BABY_LEVIATHAN_BITE);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.root, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.rotate(this.belly, (float)Math.toRadians(-15.0), 0.0f, 0.0f);
        this.animator.rotate(this.tail, (float)Math.toRadians(-17.5), 0.0f, 0.0f);
        this.animator.rotate(this.maw, (float)Math.toRadians(20.0), 0.0f, 0.0f);
        this.animator.rotate(this.skul, (float)Math.toRadians(-30.0), 0.0f, 0.0f);
        this.animator.rotate(this.mouth1, (float)Math.toRadians(22.5), (float)Math.toRadians(15.0), (float)Math.toRadians(10.0));
        this.animator.rotate(this.mouth2, (float)Math.toRadians(22.5), (float)Math.toRadians(-20.0), (float)Math.toRadians(-12.5));
        this.animator.rotate(this.mouth3, (float)Math.toRadians(-22.5), (float)Math.toRadians(22.5), (float)Math.toRadians(-2.5));
        this.animator.rotate(this.mouth4, (float)Math.toRadians(-25.0), (float)Math.toRadians(-22.5), (float)Math.toRadians(2.5));
        this.animator.endKeyframe();
        this.animator.startKeyframe(2);
        this.animator.rotate(this.root, (float)Math.toRadians(-1.25), 0.0f, 0.0f);
        this.animator.move(this.root, 0.0f, 0.0f, -2.0f);
        this.animator.rotate(this.belly, (float)Math.toRadians(37.5), 0.0f, 0.0f);
        this.animator.rotate(this.tail, (float)Math.toRadians(-1.25), 0.0f, 0.0f);
        this.animator.rotate(this.maw, (float)Math.toRadians(30.0), 0.0f, 0.0f);
        this.animator.rotate(this.skul, (float)Math.toRadians(-47.5), 0.0f, 0.0f);
        this.animator.rotate(this.mouth1, (float)Math.toRadians(32.5), (float)Math.toRadians(22.5), (float)Math.toRadians(15.0));
        this.animator.rotate(this.mouth2, (float)Math.toRadians(35.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(-17.5));
        this.animator.rotate(this.mouth3, (float)Math.toRadians(-35.0), (float)Math.toRadians(35.0), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.mouth4, (float)Math.toRadians(-37.5), (float)Math.toRadians(-35.0), (float)Math.toRadians(5.0));
        this.animator.endKeyframe();
        this.animator.startKeyframe(2);
        this.animator.rotate(this.root, (float)Math.toRadians(7.5), 0.0f, 0.0f);
        this.animator.move(this.root, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.belly, (float)Math.toRadians(22.5), 0.0f, 0.0f);
        this.animator.rotate(this.tail, (float)Math.toRadians(15.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.resetKeyframe(5);
        this.animator.setAnimation(The_Baby_Leviathan_Entity.BABY_LEVIATHAN_ABYSS_BLAST);
        this.animator.startKeyframe(20);
        this.animator.rotate(this.mouth1, (float)Math.toRadians(2.5), (float)Math.toRadians(5.0), 0.0f);
        this.animator.rotate(this.mouth2, (float)Math.toRadians(2.5), (float)Math.toRadians(-5.0), 0.0f);
        this.animator.rotate(this.mouth3, (float)Math.toRadians(-15.0), (float)Math.toRadians(7.5), 0.0f);
        this.animator.rotate(this.mouth4, (float)Math.toRadians(-15.0), (float)Math.toRadians(-7.5), 0.0f);
        this.animator.rotate(this.maw, (float)Math.toRadians(10.0), 0.0f, 0.0f);
        this.animator.rotate(this.skul, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.rotate(this.tail, (float)Math.toRadians(15.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(35);
        this.animator.startKeyframe(2);
        this.animator.rotate(this.mouth1, (float)Math.toRadians(37.5), (float)Math.toRadians(40.0), 0.0f);
        this.animator.rotate(this.mouth2, (float)Math.toRadians(37.5), (float)Math.toRadians(-40.0), 0.0f);
        this.animator.rotate(this.mouth3, (float)Math.toRadians(-37.5), (float)Math.toRadians(40.0), 0.0f);
        this.animator.rotate(this.mouth4, (float)Math.toRadians(-37.5), (float)Math.toRadians(-40.0), 0.0f);
        this.animator.rotate(this.maw, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.rotate(this.skul, (float)Math.toRadians(-20.0), 0.0f, 0.0f);
        this.animator.rotate(this.tail, (float)Math.toRadians(25.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(80);
        this.animator.resetKeyframe(20);
    }

    public void setupAnim(The_Baby_Leviathan_Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.animate(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
        float swimSpeed = 0.1f;
        float swimDegree = 0.4f;
        float finspeed = 0.1f;
        float finDegree = 0.2f;
        AdvancedModelBox[] tailBoxes = new AdvancedModelBox[]{this.tail, this.tail_back};
        AdvancedModelBox[] rt = new AdvancedModelBox[]{this.r_tentacle, this.r_tentacle};
        AdvancedModelBox[] lt = new AdvancedModelBox[]{this.l_tentacle, this.l_tentacle2};
        float partialTick = Minecraft.getInstance().getDeltaTracker().getGameTimeDeltaPartialTick(true);
        float sitProgress = entityIn.prevSitProgress + (entityIn.sitProgress - entityIn.prevSitProgress) * partialTick;
        float swimProgress = entityIn.prevSwimProgress + (entityIn.SwimProgress - entityIn.prevSwimProgress) * partialTick;
        this.progressRotationPrev(this.r_fin, swimProgress, 0.0f, 0.0f, (float)Math.toRadians(2.5), 5.0f);
        this.progressRotationPrev(this.l_fin, swimProgress, 0.0f, 0.0f, (float)Math.toRadians(-2.5), 5.0f);
        this.progressRotationPrev(this.r_down_fin, swimProgress, 0.0f, 0.0f, (float)Math.toRadians(30.0), 5.0f);
        this.progressRotationPrev(this.l_down_fin, swimProgress, 0.0f, 0.0f, (float)Math.toRadians(-30.0), 5.0f);
        this.progressRotationPrev(this.main_belly, sitProgress, 0.0f, (float)Math.toRadians(20.0), 0.0f, 5.0f);
        this.progressRotationPrev(this.r_tentacle, sitProgress, 0.0f, 0.0f, (float)Math.toRadians(-35.0), 5.0f);
        this.progressRotationPrev(this.l_tentacle, sitProgress, (float)Math.toRadians(-2.5), (float)Math.toRadians(-22.5), (float)Math.toRadians(25.0), 5.0f);
        this.progressRotationPrev(this.belly, sitProgress, 0.0f, (float)Math.toRadians(30.0), 0.0f, 5.0f);
        this.progressRotationPrev(this.tail, sitProgress, 0.0f, (float)Math.toRadians(32.5), 0.0f, 5.0f);
        this.progressRotationPrev(this.tail_back, sitProgress, 0.0f, (float)Math.toRadians(35.0), 0.0f, 5.0f);
        this.progressRotationPrev(this.skul, sitProgress, (float)Math.toRadians(7.5), (float)Math.toRadians(-22.5), 0.0f, 5.0f);
        this.progressRotationPrev(this.maw, sitProgress, (float)Math.toRadians(7.5), (float)Math.toRadians(-22.5), 0.0f, 5.0f);
        this.progressRotationPrev(this.main_mouth, sitProgress, (float)Math.toRadians(7.5), (float)Math.toRadians(-22.5), 0.0f, 5.0f);
        this.flap(this.l_hook3, swimSpeed * 0.2f, 0.35f, true, 0.0f, -0.35f, ageInTicks, 1.0f);
        this.swing(this.l_hook1, swimSpeed * 0.2f, 0.35f, true, 0.0f, -0.35f, ageInTicks, 1.0f);
        this.swing(this.l_hook1, swimSpeed * 0.2f, 0.35f, false, 0.0f, -0.35f, ageInTicks, 1.0f);
        this.flap(this.l_hook4, swimSpeed * 0.2f, 0.35f, false, 0.0f, -0.35f, ageInTicks, 1.0f);
        this.flap(this.l_hook3, swimSpeed * 1.3f, 0.35f, true, 0.0f, -0.35f, limbSwing, limbSwingAmount);
        this.swing(this.l_hook2, swimSpeed * 1.3f, 0.35f, true, 0.0f, -0.35f, limbSwing, limbSwingAmount);
        this.swing(this.l_hook2, swimSpeed * 1.3f, 0.35f, false, 0.0f, -0.35f, limbSwing, limbSwingAmount);
        this.flap(this.l_hook4, swimSpeed * 1.3f, 0.35f, false, 0.0f, -0.35f, limbSwing, limbSwingAmount);
        float walkSwingAmount = limbSwingAmount * (1.0f - 0.2f * swimProgress);
        float swimSwingAmount = limbSwingAmount * 0.2f * swimProgress;
        this.flap(this.r_fin, finspeed * 4.0f, finDegree, false, 0.0f, -0.2f, limbSwing, swimSwingAmount);
        this.flap(this.l_fin, finspeed * 4.0f, finDegree, true, 0.0f, -0.2f, limbSwing, swimSwingAmount);
        this.flap(this.r_down_fin, finspeed * 4.0f, finDegree * 1.5f, false, 0.0f, -0.3f, limbSwing, swimSwingAmount);
        this.flap(this.l_down_fin, finspeed * 4.0f, finDegree * 1.5f, true, 0.0f, -0.3f, limbSwing, swimSwingAmount);
        float walkSpeed = 1.0f;
        float walkDegree = 0.7f;
        float f1 = walkDegree * 0.15f;
        float headUp = 1.6f * Math.min(0.0f, (float)(Math.sin(limbSwing * walkSpeed) * (double)walkSwingAmount * (double)f1 * 9.0 - (double)(walkSwingAmount * f1) * 9.0));
        this.head.rotationPointY += headUp;
        this.head.rotationPointZ += (float)(Math.sin(limbSwing * walkSpeed - 1.5f) * (double)walkSwingAmount * (double)f1 * 9.0 - (double)(walkSwingAmount * f1) * 9.0);
        this.r_fin.rotationPointY += headUp;
        this.l_fin.rotationPointY += headUp;
        this.r_down_fin.rotationPointY += headUp;
        this.l_down_fin.rotationPointY += headUp;
        this.walk(this.tail, walkSpeed, walkDegree * 0.5f, true, 1.0f, 0.04f, limbSwing, walkSwingAmount);
        this.walk(this.tail_back, walkSpeed, walkDegree * 0.65f, false, 2.0f, -0.04f, limbSwing, walkSwingAmount);
        this.walk(this.head, walkSpeed, walkDegree * 0.5f, false, 0.0f, 0.04f, limbSwing, walkSwingAmount);
        this.flap(this.r_fin, walkSpeed, walkDegree, true, 3.0f, -0.3f, limbSwing, walkSwingAmount);
        this.flap(this.l_fin, walkSpeed, walkDegree, false, 3.0f, -0.3f, limbSwing, walkSwingAmount);
        this.swing(this.r_fin, walkSpeed, walkDegree, false, 2.0f, -0.3f, limbSwing, walkSwingAmount);
        this.swing(this.l_fin, walkSpeed, walkDegree, true, 2.0f, -0.3f, limbSwing, walkSwingAmount);
        this.flap(this.r_down_fin, walkSpeed, walkDegree * 0.5f, true, 3.0f, -0.15f, limbSwing, walkSwingAmount);
        this.flap(this.l_down_fin, walkSpeed, walkDegree * 0.5f, false, 3.0f, -0.15f, limbSwing, walkSwingAmount);
        this.swing(this.r_down_fin, walkSpeed, walkDegree, false, 2.0f, -0.3f, limbSwing, walkSwingAmount);
        this.swing(this.l_down_fin, walkSpeed, walkDegree, true, 2.0f, -0.3f, limbSwing, walkSwingAmount);
        this.chainSwing(tailBoxes, swimSpeed * 0.4f, swimDegree * 0.45f, -1.0, ageInTicks, 1.0f);
        this.chainSwing(tailBoxes, swimSpeed * 4.0f, swimDegree * 0.6f, -1.0, limbSwing, limbSwingAmount);
        this.chainWave(rt, 0.03f, -0.1f, -3.0, ageInTicks, 1.0f);
        this.chainSwing(rt, 0.03f, -0.1f, -3.0, ageInTicks, 1.0f);
        this.chainWave(lt, 0.03f, 0.1f, -3.0, ageInTicks, 1.0f);
        this.chainSwing(lt, 0.03f, 0.1f, -3.0, ageInTicks, 1.0f);
        this.root.rotateAngleX += headPitch * ((float)Math.PI / 180);
        this.root.rotateAngleY += netHeadYaw * ((float)Math.PI / 180);
    }

    public Iterable<AdvancedModelBox> getAllParts() {
        return ImmutableList.of(this.root, this.body, this.main_belly, this.r_tentacle, this.r_tentacle2, this.r_hook1, this.r_hook2, this.r_hook3, this.r_hook4, this.l_tentacle, this.l_tentacle2, this.l_hook1, (Object[])new AdvancedModelBox[]{this.l_hook2, this.l_hook3, this.l_hook4, this.belly, this.r_down_fin, this.l_down_fin, this.tail, this.tail_back, this.r_spike1, this.r_spike2, this.head, this.maw, this.skul, this.main_mouth, this.mouth1, this.mouth1_e, this.mouth2, this.mouth2_e, this.mouth3, this.mouth3_e, this.mouth4, this.mouth4_e, this.r_fin, this.l_fin, this.l_spike1, this.l_spike2});
    }

    public BasicModelPart root() {
        return this.root;
    }

    public void setRotationAngle(AdvancedModelBox AdvancedModelBox2, float x, float y, float z) {
        AdvancedModelBox2.rotateAngleX = x;
        AdvancedModelBox2.rotateAngleY = y;
        AdvancedModelBox2.rotateAngleZ = z;
    }
}

