/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.skd.nautilusapi.client.model.Animations.ModelAnimator
 *  com.skd.nautilusapi.client.model.tools.AdvancedEntityModel
 *  com.skd.nautilusapi.client.model.tools.AdvancedModelBox
 *  com.skd.nautilusapi.client.model.tools.BasicModelPart
 *  com.skd.nautilusapi.server.animation.IAnimatedEntity
 *  com.google.common.collect.ImmutableList
 *  com.mojang.blaze3d.vertex.PoseStack
 */
package com.skd.cataclysmbosses.client.model.entity;

import com.skd.cataclysmbosses.entity.AnimationMonster.BossMonsters.The_Harbinger_Entity;
import com.skd.nautilusapi.client.model.Animations.ModelAnimator;
import com.skd.nautilusapi.client.model.tools.AdvancedEntityModel;
import com.skd.nautilusapi.client.model.tools.AdvancedModelBox;
import com.skd.nautilusapi.client.model.tools.BasicModelPart;
import com.skd.nautilusapi.server.animation.IAnimatedEntity;
import com.google.common.collect.ImmutableList;
import com.mojang.blaze3d.vertex.PoseStack;

public class The_Harbinger_Model
extends AdvancedEntityModel<The_Harbinger_Entity> {
    private final AdvancedModelBox root;
    private final AdvancedModelBox mid;
    private final AdvancedModelBox main_head;
    private final AdvancedModelBox head;
    private final AdvancedModelBox headgear;
    private final AdvancedModelBox eyebrows;
    private final AdvancedModelBox jaw;
    private final AdvancedModelBox righthead;
    private final AdvancedModelBox rightlaser;
    private final AdvancedModelBox rightlaser2;
    private final AdvancedModelBox right_guard;
    private final AdvancedModelBox right_upper_guard;
    private final AdvancedModelBox right_lower_guard;
    private final AdvancedModelBox lefthead;
    private final AdvancedModelBox left_side_guard;
    private final AdvancedModelBox left_upper_guard;
    private final AdvancedModelBox left_lower_guard;
    private final AdvancedModelBox leftlaser;
    private final AdvancedModelBox leftlaser2;
    private final AdvancedModelBox body;
    public final AdvancedModelBox nether_star;
    private final AdvancedModelBox tail;
    private final AdvancedModelBox tailbone;
    private final AdvancedModelBox jetpack;
    private final AdvancedModelBox rightside;
    private final AdvancedModelBox rightedge1;
    private final AdvancedModelBox rightedge2;
    private final AdvancedModelBox rightedge3;
    private final AdvancedModelBox right_jet;
    private final AdvancedModelBox leftside;
    private final AdvancedModelBox leftedge1;
    private final AdvancedModelBox leftedge2;
    private final AdvancedModelBox leftedge3;
    private final AdvancedModelBox left_jet;
    private ModelAnimator animator;

    public The_Harbinger_Model() {
        this.texWidth = 128;
        this.texHeight = 128;
        this.root = new AdvancedModelBox((AdvancedEntityModel)this);
        this.root.setRotationPoint(0.0f, 24.0f, 0.0f);
        this.mid = new AdvancedModelBox((AdvancedEntityModel)this);
        this.mid.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.root.addChild((BasicModelPart)this.mid);
        this.main_head = new AdvancedModelBox((AdvancedEntityModel)this);
        this.main_head.setRotationPoint(0.0f, -7.25f, 2.0f);
        this.mid.addChild((BasicModelPart)this.main_head);
        this.setRotationAngle(this.main_head, 0.2182f, 0.0f, 0.0f);
        this.head = new AdvancedModelBox((AdvancedEntityModel)this);
        this.head.setRotationPoint(0.0f, -1.0f, 0.0f);
        this.main_head.addChild((BasicModelPart)this.head);
        this.head.setTextureOffset(0, 42).addBox(-4.0f, -6.0f, -6.0f, 8.0f, 8.0f, 8.0f, 0.0f, false);
        this.headgear = new AdvancedModelBox((AdvancedEntityModel)this);
        this.headgear.setRotationPoint(-0.5f, -5.0f, 1.0f);
        this.head.addChild((BasicModelPart)this.headgear);
        this.headgear.setTextureOffset(30, 11).addBox(-3.5f, 0.0f, -8.0f, 8.0f, 5.0f, 9.0f, 0.2f, false);
        this.headgear.setTextureOffset(51, 7).addBox(-1.5f, 2.0f, -8.0f, 4.0f, 2.0f, 1.0f, 0.15f, false);
        this.headgear.setTextureOffset(76, 73).addBox(-5.75f, -0.25f, -6.0f, 2.0f, 6.0f, 5.0f, 0.0f, false);
        this.headgear.setTextureOffset(76, 73).addBox(4.75f, -0.25f, -6.0f, 2.0f, 6.0f, 5.0f, 0.0f, true);
        this.eyebrows = new AdvancedModelBox((AdvancedEntityModel)this);
        this.eyebrows.setRotationPoint(-0.5f, 3.0f, -2.0f);
        this.head.addChild((BasicModelPart)this.eyebrows);
        this.eyebrows.setTextureOffset(39, 5).addBox(-2.5f, -7.5f, -4.25f, 6.0f, 2.0f, 0.0f, 0.0f, false);
        this.jaw = new AdvancedModelBox((AdvancedEntityModel)this);
        this.jaw.setRotationPoint(0.0f, 0.25f, 0.0f);
        this.main_head.addChild((BasicModelPart)this.jaw);
        this.jaw.setTextureOffset(58, 18).addBox(-4.0f, 1.0f, -6.0f, 8.0f, 0.0f, 8.0f, 0.0f, false);
        this.jaw.setTextureOffset(33, 26).addBox(-4.0f, -6.0f, -6.0f, 8.0f, 8.0f, 8.0f, -0.01f, false);
        this.righthead = new AdvancedModelBox((AdvancedEntityModel)this);
        this.righthead.setRotationPoint(-10.0f, -5.0f, 1.0f);
        this.mid.addChild((BasicModelPart)this.righthead);
        this.setRotationAngle(this.righthead, 0.3491f, 0.1309f, 0.0f);
        this.righthead.setTextureOffset(51, 73).addBox(-4.0f, -4.0f, -4.0f, 6.0f, 6.0f, 6.0f, 0.0f, false);
        this.rightlaser = new AdvancedModelBox((AdvancedEntityModel)this);
        this.rightlaser.setRotationPoint(-1.0f, -1.0f, 1.5f);
        this.righthead.addChild((BasicModelPart)this.rightlaser);
        this.rightlaser.setTextureOffset(77, 50).addBox(-2.0f, -2.0f, -2.5f, 4.0f, 4.0f, 3.0f, 0.0f, false);
        this.rightlaser2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.rightlaser2.setRotationPoint(0.0f, 0.0f, -0.5f);
        this.rightlaser.addChild((BasicModelPart)this.rightlaser2);
        this.rightlaser2.setTextureOffset(25, 43).addBox(-1.0f, -1.0f, -4.0f, 2.0f, 2.0f, 4.0f, 0.0f, false);
        this.rightlaser2.setTextureOffset(50, 56).addBox(-1.0f, -1.0f, -4.0f, 2.0f, 2.0f, 2.0f, 0.3f, false);
        this.right_guard = new AdvancedModelBox((AdvancedEntityModel)this);
        this.right_guard.setRotationPoint(8.0f, 20.0f, 2.25f);
        this.righthead.addChild((BasicModelPart)this.right_guard);
        this.right_upper_guard = new AdvancedModelBox((AdvancedEntityModel)this);
        this.right_upper_guard.setRotationPoint(-9.0f, -22.0f, -7.0f);
        this.right_guard.addChild((BasicModelPart)this.right_upper_guard);
        this.right_upper_guard.setTextureOffset(33, 43).addBox(-4.0f, -3.0f, 0.0f, 8.0f, 4.0f, 8.0f, 0.0f, false);
        this.right_lower_guard = new AdvancedModelBox((AdvancedEntityModel)this);
        this.right_lower_guard.setRotationPoint(-9.0f, -20.75f, -6.0f);
        this.right_guard.addChild((BasicModelPart)this.right_lower_guard);
        this.right_lower_guard.setTextureOffset(0, 60).addBox(-3.0f, -0.25f, -1.0f, 6.0f, 3.0f, 8.0f, 0.1f, false);
        this.lefthead = new AdvancedModelBox((AdvancedEntityModel)this);
        this.lefthead.setRotationPoint(10.0f, -5.0f, 1.0f);
        this.mid.addChild((BasicModelPart)this.lefthead);
        this.setRotationAngle(this.lefthead, 0.3491f, -0.1309f, 0.0f);
        this.lefthead.setTextureOffset(51, 73).addBox(-2.0f, -4.0f, -4.0f, 6.0f, 6.0f, 6.0f, 0.0f, true);
        this.left_side_guard = new AdvancedModelBox((AdvancedEntityModel)this);
        this.left_side_guard.setRotationPoint(1.0f, -1.0f, -0.75f);
        this.lefthead.addChild((BasicModelPart)this.left_side_guard);
        this.left_upper_guard = new AdvancedModelBox((AdvancedEntityModel)this);
        this.left_upper_guard.setRotationPoint(0.0f, -1.0f, -4.0f);
        this.left_side_guard.addChild((BasicModelPart)this.left_upper_guard);
        this.left_upper_guard.setTextureOffset(33, 43).addBox(-4.0f, -3.0f, 0.0f, 8.0f, 4.0f, 8.0f, 0.0f, true);
        this.left_lower_guard = new AdvancedModelBox((AdvancedEntityModel)this);
        this.left_lower_guard.setRotationPoint(0.0f, 0.25f, -3.0f);
        this.left_side_guard.addChild((BasicModelPart)this.left_lower_guard);
        this.left_lower_guard.setTextureOffset(0, 60).addBox(-3.0f, -0.25f, -1.0f, 6.0f, 3.0f, 8.0f, 0.1f, true);
        this.leftlaser = new AdvancedModelBox((AdvancedEntityModel)this);
        this.leftlaser.setRotationPoint(1.0f, -1.0f, 1.5f);
        this.lefthead.addChild((BasicModelPart)this.leftlaser);
        this.leftlaser.setTextureOffset(77, 50).addBox(-2.0f, -2.0f, -2.5f, 4.0f, 4.0f, 3.0f, 0.0f, false);
        this.leftlaser2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.leftlaser2.setRotationPoint(0.0f, 0.0f, -2.5f);
        this.leftlaser.addChild((BasicModelPart)this.leftlaser2);
        this.leftlaser2.setTextureOffset(25, 43).addBox(-1.0f, -1.0f, -2.0f, 2.0f, 2.0f, 4.0f, 0.0f, false);
        this.leftlaser2.setTextureOffset(50, 56).addBox(-1.0f, -1.0f, -2.0f, 2.0f, 2.0f, 2.0f, 0.3f, false);
        this.body = new AdvancedModelBox((AdvancedEntityModel)this);
        this.body.setRotationPoint(0.0f, -5.0f, 2.0f);
        this.mid.addChild((BasicModelPart)this.body);
        this.setRotationAngle(this.body, 0.3491f, 0.0f, 0.0f);
        this.body.setTextureOffset(32, 0).addBox(-9.0f, -0.4434f, -1.1553f, 18.0f, 2.0f, 2.0f, 0.0f, false);
        this.body.setTextureOffset(0, 0).addBox(-6.0f, 1.0566f, -7.1553f, 12.0f, 12.0f, 7.0f, 0.0f, false);
        this.body.setTextureOffset(17, 78).addBox(-1.0f, 0.5566f, -1.1553f, 2.0f, 13.0f, 2.0f, 0.0f, false);
        this.body.setTextureOffset(24, 68).addBox(-4.0f, 2.5566f, -5.6553f, 8.0f, 6.0f, 5.0f, 0.0f, false);
        this.body.setTextureOffset(26, 80).addBox(-1.0f, 0.5f, 0.75f, 2.0f, 4.0f, 4.0f, 0.0f, false);
        this.nether_star = new AdvancedModelBox((AdvancedEntityModel)this);
        this.nether_star.setRotationPoint(0.0f, 3.0f, -2.75f);
        this.body.addChild((BasicModelPart)this.nether_star);
        this.tail = new AdvancedModelBox((AdvancedEntityModel)this);
        this.tail.setRotationPoint(0.0f, 13.5566f, -0.1553f);
        this.body.addChild((BasicModelPart)this.tail);
        this.setRotationAngle(this.tail, 0.5236f, 0.0f, 0.0f);
        this.tail.setTextureOffset(81, 0).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 6.0f, 2.0f, 0.0f, false);
        this.tail.setTextureOffset(60, 37).addBox(-4.0f, -2.0f, -6.0f, 8.0f, 6.0f, 6.0f, 0.0f, false);
        this.tailbone = new AdvancedModelBox((AdvancedEntityModel)this);
        this.tailbone.setRotationPoint(0.0f, 6.0f, 0.0f);
        this.tail.addChild((BasicModelPart)this.tailbone);
        this.setRotationAngle(this.tailbone, 0.5672f, 0.0f, 0.0f);
        this.tailbone.setTextureOffset(39, 80).addBox(0.0f, 0.0f, 0.0f, 0.0f, 5.0f, 4.0f, 0.0f, false);
        this.jetpack = new AdvancedModelBox((AdvancedEntityModel)this);
        this.jetpack.setRotationPoint(0.0f, 3.0f, 4.5f);
        this.body.addChild((BasicModelPart)this.jetpack);
        this.setRotationAngle(this.jetpack, 0.2618f, 0.0f, 0.0f);
        this.rightside = new AdvancedModelBox((AdvancedEntityModel)this);
        this.rightside.setRotationPoint(0.0f, 0.5846f, -0.1554f);
        this.jetpack.addChild((BasicModelPart)this.rightside);
        this.setRotationAngle(this.rightside, -0.0436f, -0.9163f, 0.1745f);
        this.rightside.setTextureOffset(0, 20).addBox(-3.8071f, -11.8715f, 8.293f, 8.0f, 13.0f, 8.0f, 0.0f, false);
        this.rightside.setTextureOffset(66, 27).addBox(-2.8071f, 1.1285f, 9.293f, 6.0f, 3.0f, 6.0f, 0.0f, false);
        this.rightside.setTextureOffset(25, 56).addBox(-3.8071f, -2.1215f, 8.293f, 8.0f, 3.0f, 8.0f, 0.5f, false);
        this.rightside.setTextureOffset(56, 5).addBox(-3.8071f, -6.1215f, 8.293f, 8.0f, 3.0f, 8.0f, 0.5f, false);
        this.rightside.setTextureOffset(0, 72).addBox(0.1929f, -4.8715f, 0.293f, 0.0f, 8.0f, 8.0f, 0.0f, false);
        this.rightedge1 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.rightedge1.setRotationPoint(-1.25f, 3.0f, 13.25f);
        this.rightside.addChild((BasicModelPart)this.rightedge1);
        this.setRotationAngle(this.rightedge1, 0.0f, 1.5708f, 0.0f);
        this.rightedge1.setTextureOffset(58, 56).addBox(1.0f, -5.0f, 1.0f, 6.0f, 10.0f, 6.0f, 0.0f, false);
        this.rightedge2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.rightedge2.setRotationPoint(-1.25f, 3.0f, 11.25f);
        this.rightside.addChild((BasicModelPart)this.rightedge2);
        this.rightedge2.setTextureOffset(58, 56).addBox(1.0f, -5.0f, 1.0f, 6.0f, 10.0f, 6.0f, 0.0f, false);
        this.rightedge3 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.rightedge3.setRotationPoint(0.75f, 3.0f, 11.25f);
        this.rightside.addChild((BasicModelPart)this.rightedge3);
        this.setRotationAngle(this.rightedge3, 0.0f, -1.5708f, 0.0f);
        this.rightedge3.setTextureOffset(58, 56).addBox(1.0f, -5.0f, 1.0f, 6.0f, 10.0f, 6.0f, 0.0f, false);
        this.right_jet = new AdvancedModelBox((AdvancedEntityModel)this);
        this.right_jet.setRotationPoint(2.1929f, 1.1285f, 14.293f);
        this.rightside.addChild((BasicModelPart)this.right_jet);
        this.leftside = new AdvancedModelBox((AdvancedEntityModel)this);
        this.leftside.setRotationPoint(0.0f, 0.5846f, -0.1554f);
        this.jetpack.addChild((BasicModelPart)this.leftside);
        this.setRotationAngle(this.leftside, -0.0436f, 0.9163f, -0.1745f);
        this.leftside.setTextureOffset(0, 20).addBox(-4.1929f, -11.8715f, 8.293f, 8.0f, 13.0f, 8.0f, 0.0f, true);
        this.leftside.setTextureOffset(66, 27).addBox(-3.1929f, 1.1285f, 9.293f, 6.0f, 3.0f, 6.0f, 0.0f, true);
        this.leftside.setTextureOffset(25, 56).addBox(-4.1929f, -2.1215f, 8.293f, 8.0f, 3.0f, 8.0f, 0.5f, true);
        this.leftside.setTextureOffset(56, 5).addBox(-4.1929f, -6.1215f, 8.293f, 8.0f, 3.0f, 8.0f, 0.5f, true);
        this.leftside.setTextureOffset(0, 72).addBox(-0.1929f, -4.8715f, 0.293f, 0.0f, 8.0f, 8.0f, 0.0f, true);
        this.leftedge1 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.leftedge1.setRotationPoint(-1.25f, 3.0f, 11.25f);
        this.leftside.addChild((BasicModelPart)this.leftedge1);
        this.leftedge1.setTextureOffset(58, 56).addBox(1.0f, -5.0f, 1.0f, 6.0f, 10.0f, 6.0f, 0.0f, false);
        this.leftedge2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.leftedge2.setRotationPoint(0.75f, 3.0f, 11.25f);
        this.leftside.addChild((BasicModelPart)this.leftedge2);
        this.setRotationAngle(this.leftedge2, 0.0f, -1.5708f, 0.0f);
        this.leftedge2.setTextureOffset(58, 56).addBox(1.0f, -5.0f, 1.0f, 6.0f, 10.0f, 6.0f, 0.0f, false);
        this.leftedge3 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.leftedge3.setRotationPoint(0.75f, 3.0f, 13.25f);
        this.leftside.addChild((BasicModelPart)this.leftedge3);
        this.setRotationAngle(this.leftedge3, 0.0f, 3.1416f, 0.0f);
        this.leftedge3.setTextureOffset(58, 56).addBox(1.0f, -5.0f, 1.0f, 6.0f, 10.0f, 6.0f, 0.0f, false);
        this.left_jet = new AdvancedModelBox((AdvancedEntityModel)this);
        this.left_jet.setRotationPoint(-2.1929f, 1.1285f, 14.293f);
        this.leftside.addChild((BasicModelPart)this.left_jet);
        this.animator = ModelAnimator.create();
        this.updateDefaultPose();
    }

    public void animate(The_Harbinger_Entity entity, float f, float f1, float f2, float f3, float f4) {
        this.resetToDefaultPose();
        this.animator.update((IAnimatedEntity)entity);
        this.animator.setAnimation(The_Harbinger_Entity.DEATHLASER_ANIMATION);
        this.animator.startKeyframe(25);
        this.animator.rotate(this.mid, (float)Math.toRadians(-37.5), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-15.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(-17.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(-7.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-15.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(30.0), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(12.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(60);
        this.animator.startKeyframe(10);
        this.animator.rotate(this.mid, (float)Math.toRadians(-12.5), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-15.0), 0.0f, 0.0f);
        this.animator.move(this.main_head, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(30.0), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(-52.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(6);
        this.animator.resetKeyframe(10);
        this.animator.setAnimation(The_Harbinger_Entity.CHARGE_ANIMATION);
        this.animator.startKeyframe(12);
        this.animator.rotate(this.mid, (float)Math.toRadians(15.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-17.5), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.rotate(this.lefthead, (float)Math.toRadians(-32.5), 0.0f, 0.0f);
        this.animator.rotate(this.righthead, (float)Math.toRadians(-32.5), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(5.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.mid, (float)Math.toRadians(30.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-22.5), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.rotate(this.lefthead, (float)Math.toRadians(-37.5), 0.0f, 0.0f);
        this.animator.rotate(this.righthead, (float)Math.toRadians(-37.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(10.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.resetKeyframe(10);
        this.animator.setAnimation(The_Harbinger_Entity.DEATH_ANIMATION);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-40.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(37.5), 0.0f, 0.0f);
        this.animator.rotate(this.righthead, 0.0f, (float)Math.toRadians(30.0), 0.0f);
        this.animator.rotate(this.lefthead, (float)Math.toRadians(2.5), (float)Math.toRadians(-35.0), 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-47.5), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(37.5), 0.0f, 0.0f);
        this.animator.rotate(this.righthead, (float)Math.toRadians(55.0), (float)Math.toRadians(72.5), 0.0f);
        this.animator.rotate(this.lefthead, (float)Math.toRadians(55.0), (float)Math.toRadians(-85.0), 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(129);
        this.animator.setAnimation(The_Harbinger_Entity.LAUNCH_ANIAMATION);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.mid, (float)Math.toRadians(-17.5), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-17.5), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.righthead, (float)Math.toRadians(-70.0), 0.0f, 0.0f);
        this.animator.rotate(this.lefthead, (float)Math.toRadians(-70.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.mid, (float)Math.toRadians(-17.5), 0.0f, (float)Math.toRadians(-5.0));
        this.animator.rotate(this.main_head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(20.0), 0.0f, 0.0f);
        this.animator.rotate(this.righthead, (float)Math.toRadians(-70.0), 0.0f, 0.0f);
        this.animator.move(this.righthead, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.lefthead, (float)Math.toRadians(-70.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(3);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.mid, (float)Math.toRadians(-17.5), 0.0f, (float)Math.toRadians(5.0));
        this.animator.rotate(this.main_head, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(25.0), 0.0f, 0.0f);
        this.animator.rotate(this.righthead, (float)Math.toRadians(-70.0), 0.0f, 0.0f);
        this.animator.move(this.righthead, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.lefthead, (float)Math.toRadians(-70.0), 0.0f, 0.0f);
        this.animator.move(this.lefthead, 0.0f, 3.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.startKeyframe(10);
        this.animator.rotate(this.mid, (float)Math.toRadians(-15.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(25.0), 0.0f, 0.0f);
        this.animator.rotate(this.righthead, (float)Math.toRadians(-60.0), 0.0f, 0.0f);
        this.animator.move(this.righthead, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.lefthead, (float)Math.toRadians(-60.0), 0.0f, 0.0f);
        this.animator.move(this.lefthead, 0.0f, 2.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.resetKeyframe(10);
        this.animator.setAnimation(The_Harbinger_Entity.MISSILE_FIRE_ANIAMATION);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.mid, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-15.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(8);
        this.animator.rotate(this.mid, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(50.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(12);
        this.animator.rotate(this.mid, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(-17.5), 0.0f, 0.0f);
        this.animator.rotate(this.rightside, (float)Math.toRadians(40.0), (float)Math.toRadians(92.5), (float)Math.toRadians(-145.0));
        this.animator.rotate(this.leftside, (float)Math.toRadians(40.0), (float)Math.toRadians(-92.5), (float)Math.toRadians(145.0));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(12);
        this.animator.rotate(this.mid, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(70.0), 0.0f, 0.0f);
        this.animator.rotate(this.rightside, (float)Math.toRadians(67.5), (float)Math.toRadians(72.5), (float)Math.toRadians(-145.0));
        this.animator.rotate(this.leftside, (float)Math.toRadians(67.5), (float)Math.toRadians(-72.5), (float)Math.toRadians(145.0));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.mid, (float)Math.toRadians(35.0), (float)Math.toRadians(-7.5), 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(70.0), 0.0f, 0.0f);
        this.animator.rotate(this.rightside, (float)Math.toRadians(67.5), (float)Math.toRadians(72.5), (float)Math.toRadians(-145.0));
        this.animator.rotate(this.leftside, (float)Math.toRadians(67.5), (float)Math.toRadians(-72.5), (float)Math.toRadians(145.0));
        this.animator.move(this.rightside, 0.0f, 0.0f, 5.0f);
        this.animator.move(this.leftside, 0.0f, 0.0f, -3.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(15);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.mid, (float)Math.toRadians(35.0), (float)Math.toRadians(7.5), 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(70.0), 0.0f, 0.0f);
        this.animator.rotate(this.rightside, (float)Math.toRadians(67.5), (float)Math.toRadians(72.5), (float)Math.toRadians(-145.0));
        this.animator.rotate(this.leftside, (float)Math.toRadians(67.5), (float)Math.toRadians(-72.5), (float)Math.toRadians(145.0));
        this.animator.move(this.rightside, 0.0f, 0.0f, -3.0f);
        this.animator.move(this.leftside, 0.0f, 0.0f, 5.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.resetKeyframe(10);
        this.animator.setAnimation(The_Harbinger_Entity.STUN_ANIAMATION);
        this.animator.startKeyframe(15);
        this.animator.rotate(this.root, (float)Math.toRadians(20.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.rotate(this.righthead, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.rotate(this.lefthead, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(70);
        this.animator.resetKeyframe(20);
        this.animator.setAnimation(The_Harbinger_Entity.MISSILE_FIRE_FAST_ANIAMATION);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.mid, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-15.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(8);
        this.animator.rotate(this.mid, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(50.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(8);
        this.animator.rotate(this.mid, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(-17.5), 0.0f, 0.0f);
        this.animator.rotate(this.rightside, (float)Math.toRadians(40.0), (float)Math.toRadians(92.5), (float)Math.toRadians(-145.0));
        this.animator.rotate(this.leftside, (float)Math.toRadians(40.0), (float)Math.toRadians(-92.5), (float)Math.toRadians(145.0));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(8);
        this.animator.rotate(this.mid, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(70.0), 0.0f, 0.0f);
        this.animator.rotate(this.rightside, (float)Math.toRadians(67.5), (float)Math.toRadians(72.5), (float)Math.toRadians(-145.0));
        this.animator.rotate(this.leftside, (float)Math.toRadians(67.5), (float)Math.toRadians(-72.5), (float)Math.toRadians(145.0));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.mid, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.rotate(this.main_head, (float)Math.toRadians(-25.0), 0.0f, 0.0f);
        this.animator.rotate(this.head, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0f, 0.0f);
        this.animator.rotate(this.jetpack, (float)Math.toRadians(70.0), 0.0f, 0.0f);
        this.animator.rotate(this.rightside, (float)Math.toRadians(67.5), (float)Math.toRadians(72.5), (float)Math.toRadians(-145.0));
        this.animator.rotate(this.leftside, (float)Math.toRadians(67.5), (float)Math.toRadians(-72.5), (float)Math.toRadians(145.0));
        this.animator.move(this.rightside, 0.0f, 0.0f, 5.0f);
        this.animator.move(this.leftside, 0.0f, 0.0f, 5.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.resetKeyframe(10);
    }

    public void setupAnim(The_Harbinger_Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.animate(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
        float idleSpeed = 0.1f;
        float idleDegree = 0.1f;
        if (entityIn.deactivateProgress == 0.0f) {
            this.walk(this.body, idleSpeed * 0.75f, idleDegree * 0.5f, true, 0.0f, -0.05f, ageInTicks, 1.0f);
            this.walk(this.tail, idleSpeed * 0.75f, idleDegree * 0.35f, true, 1.0f, -0.05f, ageInTicks, 1.0f);
        }
        this.main_head.rotateAngleY += netHeadYaw * ((float)Math.PI / 180);
        this.main_head.rotateAngleX += headPitch * ((float)Math.PI / 180);
        if (entityIn.getAnimation() != The_Harbinger_Entity.MISSILE_FIRE_ANIAMATION && entityIn.getAnimation() != The_Harbinger_Entity.DEATH_ANIMATION && entityIn.getAnimation() != The_Harbinger_Entity.LAUNCH_ANIAMATION) {
            The_Harbinger_Model.setupHeadRotation(entityIn, this.righthead, 0);
            The_Harbinger_Model.setupHeadRotation(entityIn, this.lefthead, 1);
        }
        float partialTick = ageInTicks - (float)entityIn.tickCount;
        float Laser_Mode_Progress = entityIn.prev_Laser_Mode_Progress + (entityIn.Laser_Mode_Progress - entityIn.prev_Laser_Mode_Progress) * partialTick;
        this.progressPositionPrev(this.left_upper_guard, Laser_Mode_Progress, 0.0f, 0.0f, 5.0f, 30.0f);
        this.progressPositionPrev(this.left_lower_guard, Laser_Mode_Progress, 0.0f, 0.0f, 5.0f, 30.0f);
        this.progressRotationPrev(this.left_upper_guard, Laser_Mode_Progress, (float)Math.toRadians(45.0), 0.0f, 0.0f, 30.0f);
        this.progressRotationPrev(this.left_lower_guard, Laser_Mode_Progress, (float)Math.toRadians(-45.0), 0.0f, 0.0f, 30.0f);
        this.progressPositionPrev(this.leftlaser, Laser_Mode_Progress, 0.0f, 0.0f, -6.0f, 30.0f);
        this.progressPositionPrev(this.leftlaser2, Laser_Mode_Progress, 0.0f, 0.0f, -2.0f, 30.0f);
        this.progressPositionPrev(this.right_upper_guard, Laser_Mode_Progress, 0.0f, 0.0f, 5.0f, 30.0f);
        this.progressPositionPrev(this.right_lower_guard, Laser_Mode_Progress, 0.0f, 0.0f, 5.0f, 30.0f);
        this.progressRotationPrev(this.right_upper_guard, Laser_Mode_Progress, (float)Math.toRadians(45.0), 0.0f, 0.0f, 30.0f);
        this.progressRotationPrev(this.right_lower_guard, Laser_Mode_Progress, (float)Math.toRadians(-45.0), 0.0f, 0.0f, 30.0f);
        this.progressPositionPrev(this.rightlaser, Laser_Mode_Progress, 0.0f, 0.0f, -6.0f, 30.0f);
        this.progressPositionPrev(this.rightlaser2, Laser_Mode_Progress, 0.0f, 0.0f, -2.0f, 30.0f);
        float deactivateProgress = entityIn.prevdeactivateProgress + (entityIn.deactivateProgress - entityIn.prevdeactivateProgress) * partialTick;
        this.progressRotationPrev(this.main_head, deactivateProgress, (float)Math.toRadians(45.0), 0.0f, 0.0f, 40.0f);
        this.progressRotationPrev(this.lefthead, deactivateProgress, (float)Math.toRadians(45.0), 0.0f, 0.0f, 40.0f);
        this.progressRotationPrev(this.righthead, deactivateProgress, (float)Math.toRadians(45.0), 0.0f, 0.0f, 40.0f);
    }

    private static void setupHeadRotation(The_Harbinger_Entity entityIn, AdvancedModelBox p_171073_, int p_171074_) {
        p_171073_.rotateAngleY += (entityIn.getHeadYRot(p_171074_) - entityIn.yBodyRot) * ((float)Math.PI / 180);
        p_171073_.rotateAngleX += entityIn.getHeadXRot(p_171074_) * ((float)Math.PI / 180);
    }

    public Iterable<AdvancedModelBox> getAllParts() {
        return ImmutableList.of(this.root, this.main_head, this.mid, this.head, this.headgear, this.eyebrows, this.jaw, this.righthead, this.rightlaser, this.rightlaser2, this.right_guard, this.right_upper_guard, (Object[])new AdvancedModelBox[]{this.right_lower_guard, this.lefthead, this.left_side_guard, this.left_upper_guard, this.left_lower_guard, this.leftlaser, this.leftlaser2, this.body, this.tail, this.nether_star, this.tailbone, this.jetpack, this.rightside, this.rightedge1, this.rightedge2, this.rightedge3, this.leftside, this.leftedge1, this.leftedge2, this.leftedge3, this.left_jet, this.right_jet});
    }

    public void translateToHand(PoseStack matrixStack, boolean right) {
        this.root.translateAndRotate(matrixStack);
        this.mid.translateAndRotate(matrixStack);
        this.body.translateAndRotate(matrixStack);
        this.jetpack.translateAndRotate(matrixStack);
        if (right) {
            this.rightside.translateAndRotate(matrixStack);
            this.right_jet.translateAndRotate(matrixStack);
        } else {
            this.leftside.translateAndRotate(matrixStack);
            this.left_jet.translateAndRotate(matrixStack);
        }
    }

    public BasicModelPart root() {
        return this.root;
    }

    public void setRotationAngle(AdvancedModelBox AdvancedModelBox2, float x, float y, float z) {
        AdvancedModelBox2.rotateAngleX = x;
        AdvancedModelBox2.rotateAngleY = y;
        AdvancedModelBox2.rotateAngleZ = z;
    }
}

