/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedAnimationChannel
 *  com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedAnimationChannel$Interpolations
 *  com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedAnimationChannel$Targets
 *  com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedAnimationDefinition
 *  com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedAnimationDefinition$Builder
 *  com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedKeyframe
 *  com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedKeyframeAnimations
 */
package com.skd.thesundering.client.animation;

import com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedAnimationChannel;
import com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedAnimationDefinition;
import com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedKeyframe;
import com.skd.nautilusapi.client.model.AdvancedAnimations.AdvancedKeyframeAnimations;

public class Phantom_Halberd_Animation {
    public static final AdvancedAnimationDefinition ONE = AdvancedAnimationDefinition.Builder.withLength((float)1.25f).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.ROTATION, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.degreeVec((float)0.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0833f, AdvancedKeyframeAnimations.degreeVec((float)10.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.125f, AdvancedKeyframeAnimations.degreeVec((float)7.505f, (float)-0.4332f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.3333f, AdvancedKeyframeAnimations.degreeVec((float)10.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.POSITION, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.posVec((float)0.0f, (float)-73.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0417f, AdvancedKeyframeAnimations.posVec((float)0.0f, (float)1.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.SCALE, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.scaleVec((double)0.0, (double)0.0, (double)0.0), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0833f, AdvancedKeyframeAnimations.scaleVec((double)1.0, (double)1.0, (double)1.0), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).build();
    public static final AdvancedAnimationDefinition TWO = AdvancedAnimationDefinition.Builder.withLength((float)1.25f).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.ROTATION, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.degreeVec((float)0.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0833f, AdvancedKeyframeAnimations.degreeVec((float)10.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.125f, AdvancedKeyframeAnimations.degreeVec((float)7.6778f, (float)-1.231f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.3333f, AdvancedKeyframeAnimations.degreeVec((float)10.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.POSITION, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.posVec((float)0.0f, (float)-73.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0417f, AdvancedKeyframeAnimations.posVec((float)0.0f, (float)1.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.SCALE, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.scaleVec((double)0.0, (double)0.0, (double)0.0), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0833f, AdvancedKeyframeAnimations.scaleVec((double)1.0, (double)1.0, (double)1.0), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).build();
    public static final AdvancedAnimationDefinition THREE = AdvancedAnimationDefinition.Builder.withLength((float)1.25f).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.ROTATION, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.degreeVec((float)0.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0833f, AdvancedKeyframeAnimations.degreeVec((float)10.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.125f, AdvancedKeyframeAnimations.degreeVec((float)9.5532f, (float)-1.7581f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.3333f, AdvancedKeyframeAnimations.degreeVec((float)10.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.POSITION, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.posVec((float)0.0f, (float)-73.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0417f, AdvancedKeyframeAnimations.posVec((float)0.0f, (float)1.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.SCALE, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.scaleVec((double)0.0, (double)0.0, (double)0.0), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0833f, AdvancedKeyframeAnimations.scaleVec((double)1.0, (double)1.0, (double)1.0), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).addAnimation("mid_root", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.ROTATION, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.degreeVec((float)0.0f, (float)180.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.LINEAR)})).build();
    public static final AdvancedAnimationDefinition FOUR = AdvancedAnimationDefinition.Builder.withLength((float)1.25f).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.ROTATION, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.degreeVec((float)0.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0833f, AdvancedKeyframeAnimations.degreeVec((float)10.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.125f, AdvancedKeyframeAnimations.degreeVec((float)8.6775f, (float)-0.0082f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.3333f, AdvancedKeyframeAnimations.degreeVec((float)10.0f, (float)0.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.POSITION, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.posVec((float)0.0f, (float)-73.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0417f, AdvancedKeyframeAnimations.posVec((float)0.0f, (float)1.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).addAnimation("halberd", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.SCALE, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.scaleVec((double)0.0, (double)0.0, (double)0.0), AdvancedAnimationChannel.Interpolations.CATMULLROM), new AdvancedKeyframe(0.0833f, AdvancedKeyframeAnimations.scaleVec((double)1.0, (double)1.0, (double)1.0), AdvancedAnimationChannel.Interpolations.CATMULLROM)})).addAnimation("mid_root", new AdvancedAnimationChannel(AdvancedAnimationChannel.Targets.ROTATION, new AdvancedKeyframe[]{new AdvancedKeyframe(0.0f, AdvancedKeyframeAnimations.degreeVec((float)0.0f, (float)270.0f, (float)0.0f), AdvancedAnimationChannel.Interpolations.LINEAR)})).build();
}

