/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.core.registries.Registries
 *  net.minecraft.network.chat.Component
 *  net.minecraft.resources.ResourceKey
 *  net.minecraft.world.item.CreativeModeTab
 *  net.minecraft.world.item.CreativeModeTab$Output
 *  net.minecraft.world.item.ItemStack
 *  net.minecraft.world.level.ItemLike
 *  net.neoforged.neoforge.registries.DeferredHolder
 *  net.neoforged.neoforge.registries.DeferredRegister
 */
package com.skd.cataclysmbosses.init;

import com.skd.cataclysmbosses.init.ModDataComponents;
import com.skd.cataclysmbosses.init.ModItems;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ItemLike;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ModGroup {
    public static final DeferredRegister<CreativeModeTab> DEF_REG = DeferredRegister.create((ResourceKey)Registries.CREATIVE_MODE_TAB, (String)"cataclysm");
    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ITEM = DEF_REG.register("cataclysm_item", () -> CreativeModeTab.builder().title((Component)Component.translatable((String)"itemGroup.cataclysm.item")).icon(() -> new ItemStack((ItemLike)ModItems.THE_INCINERATOR.get())).displayItems((enabledFeatures, entries) -> {
        entries.accept((ItemLike)ModItems.WITHERITE_INGOT.get());
        entries.accept((ItemLike)ModItems.ANCIENT_METAL_INGOT.get());
        entries.accept((ItemLike)ModItems.ANCIENT_METAL_NUGGET.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_INGOT.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_NUGGET.get());
        entries.accept((ItemLike)ModItems.LACRIMA.get());
        entries.accept((ItemLike)ModItems.ESSENCE_OF_THE_STORM.get());
        entries.accept((ItemLike)ModItems.IGNITIUM_INGOT.get());
        entries.accept((ItemLike)ModItems.CURSIUM_INGOT.get());
        entries.accept((ItemLike)ModItems.IGNITIUM_UPGARDE_SMITHING_TEMPLATE.get());
        entries.accept((ItemLike)ModItems.CURSIUM_UPGARDE_SMITHING_TEMPLATE.get());
        entries.accept((ItemLike)ModItems.MONSTROUS_HORN.get());
        entries.accept((ItemLike)ModItems.LAVA_POWER_CELL.get());
        entries.accept((ItemLike)ModItems.BURNING_ASHES.get());
        entries.accept((ItemLike)ModItems.DYING_EMBER.get());
        entries.accept((ItemLike)ModItems.KOBOLETON_BONE.get());
        entries.accept((ItemLike)ModItems.VOID_JAW.get());
        entries.accept((ItemLike)ModItems.CRYSTALLIZED_CORAL_FRAGMENTS.get());
        entries.accept((ItemLike)ModItems.CRYSTALLIZED_CORAL.get());
        entries.accept((ItemLike)ModItems.CORAL_CHUNK.get());
        entries.accept((ItemLike)ModItems.ABYSSAL_SACRIFICE.get());
        entries.accept((ItemLike)ModItems.NECKLACE_OF_THE_DESERT.get());
        entries.accept((ItemLike)ModItems.STRANGE_KEY.get());
        entries.accept((ItemLike)ModItems.CORAL_SPEAR.get());
        entries.accept((ItemLike)ModItems.CORAL_BARDICHE.get());
        entries.accept((ItemLike)ModItems.ATHAME.get());
        entries.accept((ItemLike)ModItems.KHOPESH.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_SWORD.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_SHOVEL.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_PICKAXE.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_AXE.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_HOE.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_TARGE.get());
        entries.accept((ItemLike)ModItems.AZURE_SEA_SHIELD.get());
        entries.accept((ItemLike)ModItems.BULWARK_OF_THE_FLAME.get());
        entries.accept((ItemLike)ModItems.GAUNTLET_OF_GUARD.get());
        entries.accept((ItemLike)ModItems.GAUNTLET_OF_BULWARK.get());
        entries.accept((ItemLike)ModItems.GAUNTLET_OF_MAELSTROM.get());
        entries.accept((ItemLike)ModItems.THE_INCINERATOR.get());
        entries.accept((ItemLike)ModItems.BELT_OF_BEGINNER.get());
        entries.accept((ItemLike)ModItems.BLAZING_GRIPS.get());
        entries.accept((ItemLike)ModItems.CHITIN_CLAW.get());
        entries.accept((ItemLike)ModItems.RING_OF_GRUDGED.get());
        entries.accept((ItemLike)ModItems.BERSERKER_SOUL_AMULET.get());
        entries.accept((ItemLike)ModItems.VITALITY_ANKH.get());
        entries.accept((ItemLike)ModItems.UNBREAKABLE_SKULL.get());
        entries.accept((ItemLike)ModItems.STURDY_BOOTS.get());
        entries.accept((ItemLike)ModItems.CURSED_BOW.get());
        entries.accept((ItemLike)ModItems.WRATH_OF_THE_DESERT.get());
        entries.accept((ItemLike)ModItems.SOUL_RENDER.get());
        entries.accept((ItemLike)ModItems.THE_ANNIHILATOR.get());
        entries.accept((ItemLike)ModItems.THE_IMMOLATOR.get());
        entries.accept((ItemLike)ModItems.MEAT_SHREDDER.get());
        ModGroup.createLaserGatling(entries);
        entries.accept((ItemLike)ModItems.WITHER_ASSULT_SHOULDER_WEAPON.get());
        entries.accept((ItemLike)ModItems.VOID_ASSULT_SHOULDER_WEAPON.get());
        entries.accept((ItemLike)ModItems.VOID_FORGE.get());
        entries.accept((ItemLike)ModItems.TIDAL_CLAWS.get());
        entries.accept((ItemLike)ModItems.INFERNAL_FORGE.get());
        entries.accept((ItemLike)ModItems.SANDSTORM_IN_A_BOTTLE.get());
        entries.accept((ItemLike)ModItems.ANCIENT_SPEAR.get());
        entries.accept((ItemLike)ModItems.ASTRAPE.get());
        entries.accept((ItemLike)ModItems.CERAUNUS.get());
        entries.accept((ItemLike)ModItems.BRONTES.get());
        entries.accept((ItemLike)ModItems.STICKY_GLOVES.get());
        entries.accept((ItemLike)ModItems.VOID_CORE.get());
        entries.accept((ItemLike)ModItems.VOID_SCATTER_ARROW.get());
        entries.accept((ItemLike)ModItems.REMNANT_SKULL.get());
        entries.accept((ItemLike)ModItems.NETHERITE_EFFIGY.get());
        entries.accept((ItemLike)ModItems.BONE_REPTILE_HELMET.get());
        entries.accept((ItemLike)ModItems.BONE_REPTILE_CHESTPLATE.get());
        entries.accept((ItemLike)ModItems.IGNITIUM_HELMET.get());
        entries.accept((ItemLike)ModItems.IGNITIUM_ELYTRA_CHESTPLATE.get());
        entries.accept((ItemLike)ModItems.IGNITIUM_CHESTPLATE.get());
        entries.accept((ItemLike)ModItems.IGNITIUM_LEGGINGS.get());
        entries.accept((ItemLike)ModItems.IGNITIUM_BOOTS.get());
        entries.accept((ItemLike)ModItems.CURSIUM_HELMET.get());
        entries.accept((ItemLike)ModItems.CURSIUM_CHESTPLATE.get());
        entries.accept((ItemLike)ModItems.CURSIUM_LEGGINGS.get());
        entries.accept((ItemLike)ModItems.CURSIUM_BOOTS.get());
        entries.accept((ItemLike)ModItems.MONSTROUS_HELM.get());
        entries.accept((ItemLike)ModItems.BLOOM_STONE_PAULDRONS.get());
        entries.accept((ItemLike)ModItems.MECH_EYE.get());
        entries.accept((ItemLike)ModItems.FLAME_EYE.get());
        entries.accept((ItemLike)ModItems.VOID_EYE.get());
        entries.accept((ItemLike)ModItems.MONSTROUS_EYE.get());
        entries.accept((ItemLike)ModItems.ABYSS_EYE.get());
        entries.accept((ItemLike)ModItems.DESERT_EYE.get());
        entries.accept((ItemLike)ModItems.CURSED_EYE.get());
        entries.accept((ItemLike)ModItems.STORM_EYE.get());
        entries.accept((ItemLike)ModItems.THE_BABY_LEVIATHAN_BUCKET.get());
        entries.accept((ItemLike)ModItems.MODERN_REMNANT_BUCKET.get());
        entries.accept((ItemLike)ModItems.NETHERITE_MINISTROSITY_BUCKET.get());
        entries.accept((ItemLike)ModItems.MUSIC_DISC_NETHERITE_MONSTROSITY.get());
        entries.accept((ItemLike)ModItems.MUSIC_DISC_ENDER_GUARDIAN.get());
        entries.accept((ItemLike)ModItems.MUSIC_DISC_IGNIS.get());
        entries.accept((ItemLike)ModItems.MUSIC_DISC_THE_HARBINGER.get());
        entries.accept((ItemLike)ModItems.MUSIC_DISC_THE_LEVIATHAN.get());
        entries.accept((ItemLike)ModItems.MUSIC_DISC_ANCIENT_REMNANT.get());
        entries.accept((ItemLike)ModItems.MUSIC_DISC_MALEDICTUS.get());
        entries.accept((ItemLike)ModItems.MUSIC_DISC_SCYLLA.get());
        entries.accept((ItemLike)ModItems.MUSIC_DISC_THE_CATACLYSM_FARER.get());
        entries.accept((ItemLike)ModItems.LIONFISH.get());
        entries.accept((ItemLike)ModItems.AMETHYST_CRAB_MEAT.get());
        entries.accept((ItemLike)ModItems.BLESSED_AMETHYST_CRAB_MEAT.get());
        entries.accept((ItemLike)ModItems.AMETHYST_CRAB_SHELL.get());
        entries.accept((ItemLike)ModItems.ENDER_GUARDIAN_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.ENDER_GOLEM_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.ENDERMAPTERA_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.NETHERITE_MONSTROSITY_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.NETHERITE_MINISTROSITY_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.IGNIS_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.IGNITED_REVENANT_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.IGNITED_BERSERKER_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.THE_HARBINGER_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.THE_PROWLER_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.THE_WATCHER_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.THE_LEVIATHAN_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.THE_BABY_LEVIATHAN_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.CORALSSUS_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.CORAL_GOLEM_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.DEEPLING_BRUTE_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.DEEPLING_WARLOCK_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.DEEPLING_PRIEST_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.DEEPLING_ANGLER_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.DEEPLING_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.LIONFISH_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.AMETHYST_CRAB_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.ANCIENT_REMNANT_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.MODERN_REMNANT_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.KOBOLEDIATOR_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.WADJET_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.KOBOLETON_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.MALEDICTUS_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.APTRGANGR_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.ELITE_DRAUGR_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.ROYAL_DRAUGR_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.DRAUGR_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.SCYLLA_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.CLAWDIAN_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.HIPPOCAMTUS_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.CINDARIA_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.URCHINKIN_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.OCTOHOST_SPAWN_EGG.get());
        entries.accept((ItemLike)ModItems.SYMBIOCTO_SPAWN_EGG.get());
    }).build());
    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> BLOCK = DEF_REG.register("cataclysm_block", () -> CreativeModeTab.builder().title((Component)Component.translatable((String)"itemGroup.cataclysm.block")).icon(() -> new ItemStack((ItemLike)ModItems.VOID_STONE.get())).displayItems((enabledFeatures, entries) -> {
        entries.accept((ItemLike)ModItems.ENDERITE_BLOCK.get());
        entries.accept((ItemLike)ModItems.WITHERITE_BLCOK.get());
        entries.accept((ItemLike)ModItems.IGNITIUM_BLOCK.get());
        entries.accept((ItemLike)ModItems.ANCIENT_METAL_BLOCK.get());
        entries.accept((ItemLike)ModItems.CURSIUM_BLOCK.get());
        entries.accept((ItemLike)ModItems.DUNGEON_BLOCK.get());
        entries.accept((ItemLike)ModItems.POLISHED_SANDSTONE.get());
        entries.accept((ItemLike)ModItems.POLISHED_END_STONE.get());
        entries.accept((ItemLike)ModItems.POLISHED_END_STONE_SLAB.get());
        entries.accept((ItemLike)ModItems.POLISHED_END_STONE_STAIRS.get());
        entries.accept((ItemLike)ModItems.CHISELED_END_STONE_BRICKS.get());
        entries.accept((ItemLike)ModItems.END_STONE_PILLAR.get());
        entries.accept((ItemLike)ModItems.VOID_INFUSED_END_STONE_BRICKS.get());
        entries.accept((ItemLike)ModItems.VOID_STONE.get());
        entries.accept((ItemLike)ModItems.VOID_CRYSTAL.get());
        entries.accept((ItemLike)ModItems.VOID_LANTERN_BLOCK.get());
        entries.accept((ItemLike)ModItems.OBSIDIAN_BRICKS.get());
        entries.accept((ItemLike)ModItems.OBSIDIAN_BRICK_SLAB.get());
        entries.accept((ItemLike)ModItems.OBSIDIAN_BRICK_STAIRS.get());
        entries.accept((ItemLike)ModItems.OBSIDIAN_FENCE.get());
        entries.accept((ItemLike)ModItems.OBSIDIAN_BRICK_WALL.get());
        entries.accept((ItemLike)ModItems.POLISHED_OBSIDIAN.get());
        entries.accept((ItemLike)ModItems.CHISELED_OBSIDIAN_BRICKS.get());
        entries.accept((ItemLike)ModItems.CHISELED_PURPUR_BLOCK.get());
        entries.accept((ItemLike)ModItems.PURPUR_WALL.get());
        entries.accept((ItemLike)ModItems.PURPUR_VOID_RUNE_TRAP_BLOCK.get());
        entries.accept((ItemLike)ModItems.END_STONE_TELEPORT_TRAP_BRICKS.get());
        entries.accept((ItemLike)ModItems.OBSIDIAN_EXPLOSION_TRAP_BRICKS.get());
        entries.accept((ItemLike)ModItems.SANDSTONE_POISON_DART_TRAP.get());
        entries.accept((ItemLike)ModItems.SANDSTONE_IGNITE_TRAP.get());
        entries.accept((ItemLike)ModItems.SANDSTONE_FALLING_TRAP.get());
        entries.accept((ItemLike)ModItems.CHORUS_STEM.get());
        entries.accept((ItemLike)ModItems.CHORUS_PLANKS.get());
        entries.accept((ItemLike)ModItems.CHORUS_SLAB.get());
        entries.accept((ItemLike)ModItems.CHORUS_STAIRS.get());
        entries.accept((ItemLike)ModItems.CHORUS_FENCE.get());
        entries.accept((ItemLike)ModItems.PRISMARINE_BRICK_FENCE.get());
        entries.accept((ItemLike)ModItems.QUARTZ_BRICK_WALL.get());
        entries.accept((ItemLike)ModItems.PRISMARINE_BRICK_WALL.get());
        entries.accept((ItemLike)ModItems.STONE_PILLAR.get());
        entries.accept((ItemLike)ModItems.CHISELED_STONE_BRICK_PILLAR.get());
        entries.accept((ItemLike)ModItems.STONE_TILES.get());
        entries.accept((ItemLike)ModItems.STONE_TILE_SLAB.get());
        entries.accept((ItemLike)ModItems.STONE_TILE_STAIRS.get());
        entries.accept((ItemLike)ModItems.STONE_TILE_WALL.get());
        entries.accept((ItemLike)ModItems.BLACKSTONE_PILLAR.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_SLAB.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_STAIRS.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_WALL.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_FENCE.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_TILES.get());
        entries.accept((ItemLike)ModItems.CHISELED_AZURE_SEASTONE.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_BRICKS.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_BRICK_SLAB.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_BRICK_STAIRS.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_BRICK_WALL.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_EMPTY.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_URCHINKIN.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_CINDARIA.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_HIPPOCAMTUS.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_CLAWDIAN.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_THUNDER.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_SEA.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_UNDERWORLD.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_HARVEST.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_WISDOM.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_MURAL_SMITHING.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_SCYLLA_7.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_SCYLLA_8.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_SCYLLA_9.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_CLAWDIAN_3.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_CLAWDIAN_4.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_HIPPOCAMTUS_3.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_HIPPOCAMTUS_4.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_CINDARIA_3.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_CINDARIA_4.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_SCYLLA_4.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_SCYLLA_5.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_SCYLLA_6.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_CLAWDIAN_1.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_CLAWDIAN_2.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_HIPPOCAMTUS_1.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_HIPPOCAMTUS_2.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_CINDARIA_1.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_CINDARIA_2.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_SCYLLA_1.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_SCYLLA_2.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_SCYLLA_3.get());
        entries.accept((ItemLike)ModItems.CURVED_SEASTONE_URCHINKIN.get());
        entries.accept((ItemLike)ModItems.POLISHED_AZURE_SEASTONE.get());
        entries.accept((ItemLike)ModItems.POLISHED_AZURE_SEASTONE_SLAB.get());
        entries.accept((ItemLike)ModItems.POLISHED_AZURE_SEASTONE_STAIRS.get());
        entries.accept((ItemLike)ModItems.POLISHED_AZURE_SEASTONE_WALL.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_PILLAR.get());
        entries.accept((ItemLike)ModItems.AZURE_SEASTONE_PILLAR_WALL.get());
        entries.accept((ItemLike)ModItems.CHISELED_AZURE_SEASTONE_PILLAR.get());
        entries.accept((ItemLike)ModItems.CHISELED_AZURE_SEASTONE_PILLAR_WALL.get());
        entries.accept((ItemLike)ModItems.FROSTED_STONE_BRICKS.get());
        entries.accept((ItemLike)ModItems.FROSTED_STONE_BRICK_SLAB.get());
        entries.accept((ItemLike)ModItems.FROSTED_STONE_BRICK_STAIRS.get());
        entries.accept((ItemLike)ModItems.FROSTED_STONE_BRICK_WALL.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_BLOCK.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_FENCE.get());
        entries.accept((ItemLike)ModItems.BLACK_STEEL_WALL.get());
        entries.accept((ItemLike)ModItems.POINTED_ICICLE.get());
        entries.accept((ItemLike)ModItems.ALTAR_OF_FIRE.get());
        entries.accept((ItemLike)ModItems.ALTAR_OF_VOID.get());
        entries.accept((ItemLike)ModItems.ALTAR_OF_AMETHYST.get());
        entries.accept((ItemLike)ModItems.ALTAR_OF_ABYSS.get());
        entries.accept((ItemLike)ModItems.CURSED_TOMBSTONE.get());
        entries.accept((ItemLike)ModItems.EMP.get());
        entries.accept((ItemLike)ModItems.MECHANICAL_FUSION_ANVIL.get());
        entries.accept((ItemLike)ModItems.DOOR_OF_SEAL.get());
        entries.accept((ItemLike)ModItems.GODDESS_STATUE.get());
        entries.accept((ItemLike)ModItems.ABYSSAL_EGG.get());
        entries.accept((ItemLike)ModItems.APTRGANGR_HEAD.get());
        entries.accept((ItemLike)ModItems.DRAUGR_HEAD.get());
        entries.accept((ItemLike)ModItems.KOBOLEDIATOR_SKULL.get());
        entries.accept((ItemLike)ModItems.PURPUR_TILES.get());
        entries.accept((ItemLike)ModItems.PURPUR_TILE_SLAB.get());
        entries.accept((ItemLike)ModItems.PURPUR_TILE_STAIRS.get());
        entries.accept((ItemLike)ModItems.PURPUR_TILE_WALL.get());
        entries.accept((ItemLike)ModItems.PURPUR_TILE_PILLAR.get());
        entries.accept((ItemLike)ModItems.VOID_PURPUR_TILES.get());
        entries.accept((ItemLike)ModItems.POLISHED_OBSIDIAN_SLAB.get());
        entries.accept((ItemLike)ModItems.POLISHED_OBSIDIAN_STAIRS.get());
        entries.accept((ItemLike)ModItems.POLISHED_OBSIDIAN_WALL.get());
        entries.accept((ItemLike)ModItems.OBSIDIAN_PILLAR.get());
        entries.accept((ItemLike)ModItems.CHORUS_TRAPDOOR.get());
    }).withTabsBefore(new ResourceKey[]{ITEM.getKey()}).build());

    private static void createLaserGatling(CreativeModeTab.Output output) {
        ItemStack loreSword = new ItemStack((ItemLike)ModItems.LASER_GATLING.get());
        loreSword.set(ModDataComponents.LASER_GATLING, false);
        output.accept(loreSword);
    }
}

