/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.skd.nautilusapi.client.model.Animations.ModelAnimator
 *  com.skd.nautilusapi.client.model.tools.AdvancedEntityModel
 *  com.skd.nautilusapi.client.model.tools.AdvancedModelBox
 *  com.skd.nautilusapi.client.model.tools.BasicModelPart
 *  com.skd.nautilusapi.server.animation.IAnimatedEntity
 *  com.google.common.collect.ImmutableList
 */
package com.skd.sundering.client.model.entity;

import com.skd.sundering.entity.AnimationMonster.BossMonsters.Ender_Guardian_Entity;
import com.skd.nautilusapi.client.model.Animations.ModelAnimator;
import com.skd.nautilusapi.client.model.tools.AdvancedEntityModel;
import com.skd.nautilusapi.client.model.tools.AdvancedModelBox;
import com.skd.nautilusapi.client.model.tools.BasicModelPart;
import com.skd.nautilusapi.server.animation.IAnimatedEntity;
import com.google.common.collect.ImmutableList;

public class Ender_Guardian_Model
extends AdvancedEntityModel<Ender_Guardian_Entity> {
    public final AdvancedModelBox root;
    public final AdvancedModelBox lowerbody;
    public final AdvancedModelBox upperbody;
    public final AdvancedModelBox right_arm;
    public final AdvancedModelBox rightarmor;
    public final AdvancedModelBox rightarmorspike;
    public final AdvancedModelBox right_arm2;
    public final AdvancedModelBox right_fist;
    public final AdvancedModelBox left_arm;
    public final AdvancedModelBox leftarmor;
    public final AdvancedModelBox leftarmorspike;
    public final AdvancedModelBox left_arm2;
    public final AdvancedModelBox left_fist;
    public final AdvancedModelBox helmet;
    public final AdvancedModelBox head;
    public final AdvancedModelBox upperhelmet;
    public final AdvancedModelBox armor;
    public final AdvancedModelBox voidstone;
    public final AdvancedModelBox right_leg;
    public final AdvancedModelBox left_leg;
    private ModelAnimator animator;

    public Ender_Guardian_Model() {
        this.texWidth = 256;
        this.texHeight = 256;
        this.root = new AdvancedModelBox((AdvancedEntityModel)this);
        this.root.setRotationPoint(0.0f, 24.0f, 0.0f);
        this.lowerbody = new AdvancedModelBox((AdvancedEntityModel)this);
        this.lowerbody.setRotationPoint(0.0f, -22.0f, 0.0f);
        this.root.addChild((BasicModelPart)this.lowerbody);
        this.lowerbody.setTextureOffset(121, 0).addBox(-11.0f, -8.0f, -7.0f, 22.0f, 8.0f, 14.0f, 0.0f, false);
        this.upperbody = new AdvancedModelBox((AdvancedEntityModel)this);
        this.upperbody.setRotationPoint(0.0f, -7.0f, 0.0f);
        this.lowerbody.addChild((BasicModelPart)this.upperbody);
        this.upperbody.setTextureOffset(0, 0).addBox(-20.0f, -32.0f, -10.0f, 40.0f, 32.0f, 20.0f, 0.0f, false);
        this.right_arm = new AdvancedModelBox((AdvancedEntityModel)this);
        this.right_arm.setRotationPoint(-20.0f, -25.0f, 0.0f);
        this.upperbody.addChild((BasicModelPart)this.right_arm);
        this.right_arm.setTextureOffset(94, 150).addBox(-14.0f, -6.0f, -6.0f, 14.0f, 20.0f, 12.0f, 0.0f, false);
        this.rightarmor = new AdvancedModelBox((AdvancedEntityModel)this);
        this.rightarmor.setRotationPoint(-7.0f, 0.0f, -10.0f);
        this.right_arm.addChild((BasicModelPart)this.rightarmor);
        this.rightarmor.setTextureOffset(103, 35).addBox(-10.0f, -7.0f, 1.0f, 12.0f, 18.0f, 18.0f, 0.0f, false);
        this.rightarmorspike = new AdvancedModelBox((AdvancedEntityModel)this);
        this.rightarmorspike.setRotationPoint(-7.0f, -3.0f, 10.0f);
        this.rightarmor.addChild((BasicModelPart)this.rightarmorspike);
        this.setRotationAngle(this.rightarmorspike, 0.0f, 0.0f, -0.6109f);
        this.rightarmorspike.setTextureOffset(0, 162).addBox(-3.0f, -12.0f, -3.0f, 6.0f, 12.0f, 6.0f, 0.0f, false);
        this.right_arm2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.right_arm2.setRotationPoint(-8.5f, 14.0f, 0.0f);
        this.right_arm.addChild((BasicModelPart)this.right_arm2);
        this.right_arm2.setTextureOffset(146, 23).addBox(-5.5f, 0.0f, -6.0f, 10.0f, 14.0f, 12.0f, 0.0f, false);
        this.right_fist = new AdvancedModelBox((AdvancedEntityModel)this);
        this.right_fist.setRotationPoint(-5.5f, 14.0f, 0.0f);
        this.right_arm2.addChild((BasicModelPart)this.right_fist);
        this.right_fist.setTextureOffset(142, 72).addBox(0.0f, -1.0f, -6.0f, 12.0f, 12.0f, 12.0f, 0.25f, false);
        this.left_arm = new AdvancedModelBox((AdvancedEntityModel)this);
        this.left_arm.setRotationPoint(20.0f, -25.0f, 0.0f);
        this.upperbody.addChild((BasicModelPart)this.left_arm);
        this.left_arm.setTextureOffset(94, 150).addBox(0.0f, -6.0f, -6.0f, 14.0f, 20.0f, 12.0f, 0.0f, true);
        this.leftarmor = new AdvancedModelBox((AdvancedEntityModel)this);
        this.leftarmor.setRotationPoint(7.0f, 0.0f, -10.0f);
        this.left_arm.addChild((BasicModelPart)this.leftarmor);
        this.leftarmor.setTextureOffset(103, 35).addBox(-2.0f, -7.0f, 1.0f, 12.0f, 18.0f, 18.0f, 0.0f, true);
        this.leftarmorspike = new AdvancedModelBox((AdvancedEntityModel)this);
        this.leftarmorspike.setRotationPoint(7.0f, -3.0f, 10.0f);
        this.leftarmor.addChild((BasicModelPart)this.leftarmorspike);
        this.setRotationAngle(this.leftarmorspike, 0.0f, 0.0f, 0.6109f);
        this.leftarmorspike.setTextureOffset(0, 162).addBox(-3.0f, -12.0f, -3.0f, 6.0f, 12.0f, 6.0f, 0.0f, true);
        this.left_arm2 = new AdvancedModelBox((AdvancedEntityModel)this);
        this.left_arm2.setRotationPoint(8.5f, 14.0f, 0.0f);
        this.left_arm.addChild((BasicModelPart)this.left_arm2);
        this.left_arm2.setTextureOffset(146, 23).addBox(-4.5f, 0.0f, -6.0f, 10.0f, 14.0f, 12.0f, 0.0f, true);
        this.left_fist = new AdvancedModelBox((AdvancedEntityModel)this);
        this.left_fist.setRotationPoint(5.5f, 14.0f, 0.0f);
        this.left_arm2.addChild((BasicModelPart)this.left_fist);
        this.left_fist.setTextureOffset(142, 72).addBox(-12.0f, -1.0f, -6.0f, 12.0f, 12.0f, 12.0f, 0.25f, true);
        this.helmet = new AdvancedModelBox((AdvancedEntityModel)this);
        this.helmet.setRotationPoint(0.0f, -28.0f, -7.0f);
        this.upperbody.addChild((BasicModelPart)this.helmet);
        this.helmet.setTextureOffset(0, 139).addBox(-8.0f, 2.0f, -16.0f, 16.0f, 6.0f, 16.0f, 0.0f, false);
        this.helmet.setTextureOffset(58, 155).addBox(-10.0f, -1.0f, -12.0f, 6.0f, 10.0f, 7.0f, 0.0f, false);
        this.helmet.setTextureOffset(161, 114).addBox(4.0f, -1.0f, -12.0f, 6.0f, 10.0f, 7.0f, 0.0f, false);
        this.head = new AdvancedModelBox((AdvancedEntityModel)this);
        this.head.setRotationPoint(0.0f, -4.0f, -8.0f);
        this.helmet.addChild((BasicModelPart)this.head);
        this.head.setTextureOffset(49, 99).addBox(-3.0f, 0.0f, -3.0f, 6.0f, 6.0f, 6.0f, 0.0f, false);
        this.upperhelmet = new AdvancedModelBox((AdvancedEntityModel)this);
        this.upperhelmet.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.helmet.addChild((BasicModelPart)this.upperhelmet);
        this.upperhelmet.setTextureOffset(106, 121).addBox(-8.0f, -7.75f, -16.0f, 16.0f, 12.0f, 16.0f, -0.25f, false);
        this.upperhelmet.setTextureOffset(147, 150).addBox(-3.0f, -9.5f, -16.7f, 6.0f, 13.0f, 10.0f, 0.0f, false);
        this.armor = new AdvancedModelBox((AdvancedEntityModel)this);
        this.armor.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.upperbody.addChild((BasicModelPart)this.armor);
        this.armor.setTextureOffset(0, 53).addBox(-17.0f, -34.0f, -12.0f, 34.0f, 21.0f, 24.0f, 0.0f, false);
        this.armor.setTextureOffset(91, 73).addBox(-25.0f, -35.0f, -13.0f, 12.0f, 21.0f, 26.0f, 0.0f, false);
        this.armor.setTextureOffset(91, 73).addBox(13.0f, -35.0f, -13.0f, 12.0f, 21.0f, 26.0f, 0.0f, true);
        this.voidstone = new AdvancedModelBox((AdvancedEntityModel)this);
        this.voidstone.setRotationPoint(0.0f, -16.0f, 10.0f);
        this.upperbody.addChild((BasicModelPart)this.voidstone);
        this.setRotationAngle(this.voidstone, -0.7854f, 0.0f, 0.0f);
        this.voidstone.setTextureOffset(0, 99).addBox(-8.0f, -8.0f, -8.0f, 16.0f, 16.0f, 16.0f, 1.0f, false);
        this.right_leg = new AdvancedModelBox((AdvancedEntityModel)this);
        this.right_leg.setRotationPoint(-11.0f, -22.0f, 0.0f);
        this.root.addChild((BasicModelPart)this.right_leg);
        this.right_leg.setTextureOffset(49, 116).addBox(-8.0f, 0.0f, -8.0f, 12.0f, 22.0f, 16.0f, 0.0f, false);
        this.left_leg = new AdvancedModelBox((AdvancedEntityModel)this);
        this.left_leg.setRotationPoint(11.0f, -22.0f, 0.0f);
        this.root.addChild((BasicModelPart)this.left_leg);
        this.left_leg.setTextureOffset(49, 116).addBox(-4.0f, 0.0f, -8.0f, 12.0f, 22.0f, 16.0f, 0.0f, true);
        this.animator = ModelAnimator.create();
        this.updateDefaultPose();
    }

    public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4) {
        this.resetToDefaultPose();
        this.animator.update(entity);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_RIGHT_ATTACK);
        this.animator.startKeyframe(10);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(5.0), (float)Math.toRadians(32.5), (float)Math.toRadians(2.5));
        this.animator.move(this.upperbody, 0.0f, 0.0f, -1.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-5.0), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -2.0f);
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(17.5), 0.0f);
        this.animator.move(this.right_leg, 1.0f, 0.0f, 5.0f);
        this.animator.rotate(this.armor, 0.0f, 0.0f, (float)Math.toRadians(7.5));
        this.animator.move(this.armor, -3.0f, 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-17.5), 0.0f, (float)Math.toRadians(35.0));
        this.animator.move(this.right_arm, 2.0f, 1.0f, 1.0f);
        this.animator.rotate(this.rightarmor, 0.0f, 0.0f, (float)Math.toRadians(5.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-80.0), (float)Math.toRadians(-55.0), (float)Math.toRadians(15.0));
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(-25.0), (float)Math.toRadians(-2.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(7.5), (float)Math.toRadians(2.5));
        this.animator.move(this.left_arm, 1.0f, 3.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-37.5), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, -2.0f, 1.0f, 2.0f);
        this.animator.move(this.left_fist, 0.0f, -5.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(-7.5), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(35.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(-10.0));
        this.animator.move(this.upperbody, 0.0f, 0.0f, -1.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-12.5), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, 2.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
        this.animator.move(this.right_arm, -1.0f, 2.0f, -7.0f);
        this.animator.rotate(this.rightarmor, (float)Math.toRadians(10.0), 0.0f, 0.0f);
        this.animator.move(this.rightarmor, 0.0f, -7.0f, -2.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(-87.5), (float)Math.toRadians(32.5));
        this.animator.move(this.right_arm2, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm, 0.0f, -2.0f, -1.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-40.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, -2.0f, 2.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(2.5));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(7);
        this.animator.resetKeyframe(10);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_LEFT_ATTACK);
        this.animator.startKeyframe(8);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(5.0), (float)Math.toRadians(-32.5), (float)Math.toRadians(-2.5));
        this.animator.move(this.upperbody, 0.0f, 0.0f, -1.0f);
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(5.0), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -2.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-17.5), 0.0f);
        this.animator.move(this.left_leg, -1.0f, 0.0f, 5.0f);
        this.animator.rotate(this.armor, 0.0f, 0.0f, (float)Math.toRadians(-7.5));
        this.animator.move(this.armor, 3.0f, 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-17.5), 0.0f, (float)Math.toRadians(-35.0));
        this.animator.move(this.left_arm, -2.0f, 1.0f, 1.0f);
        this.animator.rotate(this.leftarmor, 0.0f, 0.0f, (float)Math.toRadians(-5.0));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-80.0), (float)Math.toRadians(55.0), (float)Math.toRadians(-15.0));
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(25.0), (float)Math.toRadians(2.5));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(-2.5));
        this.animator.move(this.right_arm, -1.0f, 3.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-37.5), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 2.0f, 1.0f, 2.0f);
        this.animator.move(this.right_fist, 0.0f, -5.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(7);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(7.5), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(35.0), (float)Math.toRadians(30.0), (float)Math.toRadians(10.0));
        this.animator.move(this.upperbody, 0.0f, 0.0f, -1.0f);
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(-12.5), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 2.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
        this.animator.move(this.left_arm, 1.0f, 2.0f, -7.0f);
        this.animator.rotate(this.leftarmor, (float)Math.toRadians(10.0), 0.0f, 0.0f);
        this.animator.move(this.leftarmor, 0.0f, -7.0f, -2.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(87.5), (float)Math.toRadians(-32.5));
        this.animator.move(this.left_arm2, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm, 0.0f, -2.0f, -1.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-40.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, -2.0f, 2.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(-12.0), (float)Math.toRadians(-2.5));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(12);
        this.animator.resetKeyframe(10);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_RIGHT_STRONG_ATTACK);
        this.animator.startKeyframe(15);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(5.0), (float)Math.toRadians(32.5), (float)Math.toRadians(2.5));
        this.animator.move(this.upperbody, 0.0f, 0.0f, -1.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-5.0), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -2.0f);
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(17.5), 0.0f);
        this.animator.move(this.right_leg, 1.0f, 0.0f, 5.0f);
        this.animator.rotate(this.armor, 0.0f, 0.0f, (float)Math.toRadians(7.5));
        this.animator.move(this.armor, -3.0f, 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-17.5), 0.0f, (float)Math.toRadians(35.0));
        this.animator.move(this.right_arm, 2.0f, 1.0f, 1.0f);
        this.animator.rotate(this.rightarmor, 0.0f, 0.0f, (float)Math.toRadians(5.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-80.0), (float)Math.toRadians(-55.0), (float)Math.toRadians(15.0));
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(-25.0), (float)Math.toRadians(-2.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(7.5), (float)Math.toRadians(2.5));
        this.animator.move(this.left_arm, 1.0f, 3.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-37.5), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, -2.0f, 1.0f, 2.0f);
        this.animator.move(this.left_fist, 0.0f, -5.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(12);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(-7.5), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(27.5), (float)Math.toRadians(-30.0), (float)Math.toRadians(-10.0));
        this.animator.move(this.upperbody, 0.0f, 0.0f, -1.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-12.5), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, 2.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-60.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
        this.animator.move(this.right_arm, -1.0f, 9.0f, 0.0f);
        this.animator.rotate(this.rightarmor, (float)Math.toRadians(10.0), 0.0f, 0.0f);
        this.animator.move(this.rightarmor, 0.0f, -7.0f, -2.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(-87.5), (float)Math.toRadians(32.5));
        this.animator.move(this.right_arm2, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm, 0.0f, -2.0f, -1.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-40.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, -2.0f, 2.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(2.5));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(13);
        this.animator.resetKeyframe(17);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_LEFT_STRONG_ATTACK);
        this.animator.startKeyframe(17);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(5.0), (float)Math.toRadians(-32.5), (float)Math.toRadians(-2.5));
        this.animator.move(this.upperbody, 0.0f, 0.0f, -1.0f);
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(5.0), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -2.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-17.5), 0.0f);
        this.animator.move(this.left_leg, -1.0f, 0.0f, 5.0f);
        this.animator.rotate(this.armor, 0.0f, 0.0f, (float)Math.toRadians(-7.5));
        this.animator.move(this.armor, 3.0f, 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-17.5), 0.0f, (float)Math.toRadians(-35.0));
        this.animator.move(this.left_arm, -2.0f, 1.0f, 1.0f);
        this.animator.rotate(this.leftarmor, 0.0f, 0.0f, (float)Math.toRadians(-5.0));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-80.0), (float)Math.toRadians(55.0), (float)Math.toRadians(-15.0));
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(25.0), (float)Math.toRadians(2.5));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(-2.5));
        this.animator.move(this.right_arm, -1.0f, 3.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-37.5), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 2.0f, 1.0f, 2.0f);
        this.animator.move(this.right_fist, 0.0f, -5.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(15);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(7.5), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(27.5), (float)Math.toRadians(30.0), (float)Math.toRadians(10.0));
        this.animator.move(this.upperbody, 0.0f, 0.0f, -1.0f);
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(-12.5), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 2.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-60.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
        this.animator.move(this.left_arm, 1.0f, 9.0f, 0.0f);
        this.animator.rotate(this.leftarmor, (float)Math.toRadians(10.0), 0.0f, 0.0f);
        this.animator.move(this.leftarmor, 0.0f, -7.0f, -2.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(87.5), (float)Math.toRadians(-32.5));
        this.animator.move(this.left_arm2, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm, 0.0f, -2.0f, -1.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-40.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, -2.0f, 2.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(-12.0), (float)Math.toRadians(-2.5));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_BURST_ATTACK);
        this.animator.startKeyframe(15);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -3.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 4.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.move(this.lowerbody, 0.0f, 0.0f, 2.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(5.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(35.0), (float)Math.toRadians(-5.5), (float)Math.toRadians(-45.0));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(35.0), (float)Math.toRadians(5.5), (float)Math.toRadians(45.0));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.left_leg, (float)Math.toRadians(5.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_leg, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, 7.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -5.0f);
        this.animator.move(this.lowerbody, 0.0f, 3.0f, 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(12.5), 0.0f, 0.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(5.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-80.0), (float)Math.toRadians(12.5), (float)Math.toRadians(-45.0));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-80.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(45.0));
        this.animator.move(this.left_arm, 0.0f, 0.0f, -10.0f);
        this.animator.move(this.right_arm, 0.0f, 0.0f, -10.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_UPPERCUT_AND_BULLET);
        this.animator.startKeyframe(15);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(12.5), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, 4.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -3.0f);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(-15.0), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-2.5), (float)Math.toRadians(-20.0), (float)Math.toRadians(5.0));
        this.animator.rotate(this.armor, 0.0f, 0.0f, (float)Math.toRadians(2.5));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(17.5), (float)Math.toRadians(-5.0), (float)Math.toRadians(10.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0f, 0.0f);
        this.animator.move(this.right_arm, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(20.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-15.0));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(20.0), 0.0f);
        this.animator.rotate(this.upperbody, 0.0f, (float)Math.toRadians(35.0), 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-50.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-52.5));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(-7.5), 0.0f);
        this.animator.rotate(this.upperbody, 0.0f, (float)Math.toRadians(-7.5), 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(35.0), (float)Math.toRadians(20.0), (float)Math.toRadians(15.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(45.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-35.0));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_STOMP);
        this.animator.startKeyframe(15);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 1.0f);
        this.animator.move(this.left_leg, 0.0f, -9.0f, -9.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-7.5), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0));
        this.animator.move(this.right_arm, -1.0f, 0.0f, 0.0f);
        this.animator.move(this.left_arm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(15);
        this.animator.startKeyframe(3);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 2.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(15.0), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-30.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-30.0), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_RAGE_STOMP);
        this.animator.startKeyframe(15);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 1.0f);
        this.animator.move(this.left_leg, 0.0f, -9.0f, -9.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-7.5), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0));
        this.animator.move(this.right_arm, -1.0f, 0.0f, 0.0f);
        this.animator.move(this.left_arm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(15);
        this.animator.startKeyframe(3);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 2.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(15.0), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-30.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-30.0), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(5);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 1.0f);
        this.animator.move(this.left_leg, 0.0f, -9.0f, -9.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-7.5), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0));
        this.animator.move(this.right_arm, -1.0f, 0.0f, 0.0f);
        this.animator.move(this.left_arm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(3);
        this.animator.startKeyframe(3);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 2.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(15.0), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-30.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-30.0), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(3);
        this.animator.startKeyframe(3);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 1.0f);
        this.animator.move(this.left_leg, 0.0f, -9.0f, -9.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-7.5), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0));
        this.animator.move(this.right_arm, -1.0f, 0.0f, 0.0f);
        this.animator.move(this.left_arm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.startKeyframe(3);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 2.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(15.0), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-30.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-30.0), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_MASS_DESTRUCTION);
        this.animator.startKeyframe(25);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-22.5), 0.0f, 0.0f);
        this.animator.rotate(this.armor, (float)Math.toRadians(-2.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-97.5), (float)Math.toRadians(25.0), (float)Math.toRadians(25.0));
        this.animator.move(this.right_arm, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-97.5), (float)Math.toRadians(-25.0), (float)Math.toRadians(-25.0));
        this.animator.move(this.left_arm, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(30.0), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(47.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-57.5), (float)Math.toRadians(25.0), (float)Math.toRadians(25.0));
        this.animator.move(this.right_arm, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-57.5), (float)Math.toRadians(-25.0), (float)Math.toRadians(-25.0));
        this.animator.move(this.left_arm, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.resetKeyframe(25);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_FALLEN);
        this.animator.startKeyframe(15);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-20.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(30.0), (float)Math.toRadians(10.0), (float)Math.toRadians(72.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(30.0), (float)Math.toRadians(-10.0), (float)Math.toRadians(-75.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(12.5), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(30.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-82.5), (float)Math.toRadians(10.0), (float)Math.toRadians(72.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-82.5), (float)Math.toRadians(-10.0), (float)Math.toRadians(-75.0));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.startKeyframe(6);
        this.animator.move(this.root, 0.0f, 14.0f, 0.0f);
        this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0f, 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(90.0), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-52.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-42.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-42.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(15);
        this.animator.move(this.root, 0.0f, 14.0f, 0.0f);
        this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0f, 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(90.0), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-57.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-60.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-60.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-35.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-35.0), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(-42.5), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(5);
        this.animator.move(this.root, 0.0f, 14.0f, 0.0f);
        this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0f, 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(90.0), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-35.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-92.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-92.5), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-35.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-35.0), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(20.0), 0.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(100);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_RAGE_UPPERCUT);
        this.animator.startKeyframe(15);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(12.5), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, 4.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -3.0f);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(-15.0), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-2.5), (float)Math.toRadians(-20.0), (float)Math.toRadians(5.0));
        this.animator.rotate(this.armor, 0.0f, 0.0f, (float)Math.toRadians(2.5));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(17.5), (float)Math.toRadians(-5.0), (float)Math.toRadians(10.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0f, 0.0f);
        this.animator.move(this.right_arm, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(20.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-15.0));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(20.0), 0.0f);
        this.animator.rotate(this.upperbody, 0.0f, (float)Math.toRadians(35.0), 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-50.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-52.5));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(-7.5), 0.0f);
        this.animator.rotate(this.upperbody, 0.0f, (float)Math.toRadians(-7.5), 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(35.0), (float)Math.toRadians(20.0), (float)Math.toRadians(15.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(45.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-35.0));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(3);
        this.animator.startKeyframe(10);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-17.5), 0.0f, 0.0f);
        this.animator.move(this.right_arm, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-115.0), 0.0f, (float)Math.toRadians(32.5));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.move(this.left_arm, 0.0f, 0.0f, -7.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-115.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(12);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(22.5), 0.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(50.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-60.0), (float)Math.toRadians(5.0), (float)Math.toRadians(32.5));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.move(this.left_arm, 0.0f, 0.0f, -7.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-60.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_HUG_ME);
        this.animator.startKeyframe(15);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(27.5), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 8.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -6.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(35.0), (float)Math.toRadians(-15.0), 0.0f);
        this.animator.move(this.upperbody, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-35.0), 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(42.5), (float)Math.toRadians(-2.5), (float)Math.toRadians(62.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(60.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-57.5));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(-25.0), (float)Math.toRadians(-7.5), 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.startKeyframe(6);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(-17.5), 0.0f);
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(25.0), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -6.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, 9.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-22.5), (float)Math.toRadians(2.5), 0.0f);
        this.animator.rotate(this.armor, 0.0f, 0.0f, (float)Math.toRadians(2.5));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-60.0), (float)Math.toRadians(5.0), (float)Math.toRadians(45.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-62.5), (float)Math.toRadians(2.5), (float)Math.toRadians(-35.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-82.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(17.5), (float)Math.toRadians(5.0));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_AIR_STRIKE1);
        this.animator.startKeyframe(15);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-15.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-10.0), (float)Math.toRadians(47.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-17.5), (float)Math.toRadians(10.0), (float)Math.toRadians(-47.5));
        this.animator.move(this.right_arm, 0.0f, 0.0f, -4.0f);
        this.animator.move(this.left_arm, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-110.0), (float)Math.toRadians(-30.0), 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-110.0), (float)Math.toRadians(30.0), 0.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(3);
        this.animator.startKeyframe(2);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-15.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-50.0), (float)Math.toRadians(-25.0), (float)Math.toRadians(32.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-50.0), (float)Math.toRadians(25.0), (float)Math.toRadians(-32.5));
        this.animator.move(this.right_arm, 2.5f, 2.0f, -6.0f);
        this.animator.move(this.left_arm, -2.75f, 2.0f, -6.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-105.0), (float)Math.toRadians(-50.0), (float)Math.toRadians(12.5));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-105.0), (float)Math.toRadians(50.0), (float)Math.toRadians(-12.5));
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.startKeyframe(8);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(-17.5), 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.move(this.lowerbody, 0.0f, 3.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-27.5), (float)Math.toRadians(-2.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-82.5), (float)Math.toRadians(17.5), (float)Math.toRadians(45.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-100.0), (float)Math.toRadians(-17.5), (float)Math.toRadians(-27.5));
        this.animator.move(this.right_arm, 2.0f, -2.0f, -2.0f);
        this.animator.move(this.left_arm, -2.0f, -1.0f, -3.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-82.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(17.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(30.0), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 2.0f, -6.0f);
        this.animator.move(this.left_leg, 0.0f, 3.0f, 9.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(60);
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_AIR_STRIKE2);
        this.animator.startKeyframe(0);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(-17.5), 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-5.0), 0.0f, 0.0f);
        this.animator.move(this.lowerbody, 0.0f, 3.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-27.5), (float)Math.toRadians(-2.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-82.5), (float)Math.toRadians(17.5), (float)Math.toRadians(45.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-100.0), (float)Math.toRadians(-17.5), (float)Math.toRadians(-27.5));
        this.animator.move(this.right_arm, 2.0f, -2.0f, -2.0f);
        this.animator.move(this.left_arm, -2.0f, -1.0f, -3.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-82.5), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(17.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(30.0), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 2.0f, -6.0f);
        this.animator.move(this.left_leg, 0.0f, 3.0f, 9.0f);
        this.animator.endKeyframe();
        this.animator.startKeyframe(4);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(-17.5), 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(35.0), 0.0f, 0.0f);
        this.animator.move(this.lowerbody, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(27.5), (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(-15.0), (float)Math.toRadians(32.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(15.0), (float)Math.toRadians(-32.5));
        this.animator.move(this.right_arm, 2.0f, 9.0f, -6.0f);
        this.animator.move(this.left_arm, -1.0f, 11.0f, -6.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(20.0), 0.0f);
        this.animator.rotate(this.left_leg, (float)Math.toRadians(-15.0), 0.0f, 0.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -6.0f);
        this.animator.move(this.left_leg, 0.0f, 1.0f, 5.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_RIGHT_SWING);
        this.animator.startKeyframe(0);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(-7.5), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(35.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(-10.0));
        this.animator.move(this.upperbody, 0.0f, 0.0f, -1.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-12.5), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, 2.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
        this.animator.move(this.right_arm, -1.0f, 2.0f, -7.0f);
        this.animator.rotate(this.rightarmor, (float)Math.toRadians(10.0), 0.0f, 0.0f);
        this.animator.move(this.rightarmor, 0.0f, -7.0f, -2.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(-87.5), (float)Math.toRadians(32.5));
        this.animator.move(this.right_arm2, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm, 0.0f, -2.0f, -1.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-40.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, -2.0f, 2.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(2.5));
        this.animator.endKeyframe();
        this.animator.startKeyframe(15);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(5.0), 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(2.5), (float)Math.toRadians(10.0), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(27.5), (float)Math.toRadians(45.0), (float)Math.toRadians(12.5));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-10.0), (float)Math.toRadians(32.5), 0.0f);
        this.animator.move(this.right_arm, 0.0f, -2.0f, -2.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-65.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, -2.0f, -2.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-57.5));
        this.animator.move(this.left_arm, 4.0f, 8.0f, -2.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, -6.0f, -6.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(-2.5));
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(12.5), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 8.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(8);
        this.animator.startKeyframe(4);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(5.0), 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(2.5), (float)Math.toRadians(10.0), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(2.5), (float)Math.toRadians(-45.0), (float)Math.toRadians(12.5));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-20.0), (float)Math.toRadians(30.0), (float)Math.toRadians(25.0));
        this.animator.move(this.right_arm, 0.0f, -2.0f, -2.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-75.0), (float)Math.toRadians(-25.0), 0.0f);
        this.animator.move(this.right_arm2, 0.0f, -2.0f, 2.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(32.5), (float)Math.toRadians(7.5), (float)Math.toRadians(-57.5));
        this.animator.move(this.left_arm, 4.0f, 8.0f, 2.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(25.0), (float)Math.toRadians(-12.5));
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(12.5), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 8.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -6.0f);
        this.animator.endKeyframe();
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_LEFT_SWING);
        this.animator.startKeyframe(0);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(7.5), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(35.0), (float)Math.toRadians(30.0), (float)Math.toRadians(10.0));
        this.animator.move(this.upperbody, 0.0f, 0.0f, -1.0f);
        this.animator.rotate(this.right_leg, 0.0f, (float)Math.toRadians(-12.5), 0.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, 2.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
        this.animator.move(this.left_arm, 1.0f, 2.0f, -7.0f);
        this.animator.rotate(this.leftarmor, (float)Math.toRadians(10.0), 0.0f, 0.0f);
        this.animator.move(this.leftarmor, 0.0f, -7.0f, -2.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(87.5), (float)Math.toRadians(-32.5));
        this.animator.move(this.left_arm2, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-10.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm, 0.0f, -2.0f, -1.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-40.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, -2.0f, 2.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(-12.0), (float)Math.toRadians(-2.5));
        this.animator.endKeyframe();
        this.animator.startKeyframe(15);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(-5.0), 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(2.5), (float)Math.toRadians(-10.0), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(27.5), (float)Math.toRadians(-45.0), (float)Math.toRadians(-12.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-32.5), 0.0f);
        this.animator.move(this.left_arm, 0.0f, -2.0f, -2.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-65.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, -2.0f, -2.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(57.5));
        this.animator.move(this.right_arm, -4.0f, 8.0f, -2.0f);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, -6.0f, 6.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(2.5));
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-12.5), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, 8.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -6.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(8);
        this.animator.startKeyframe(4);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(5.0), 0.0f);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(2.5), (float)Math.toRadians(-10.0), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(2.5), (float)Math.toRadians(45.0), (float)Math.toRadians(-12.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-20.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(-25.0));
        this.animator.move(this.left_arm, 0.0f, -2.0f, -2.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-75.0), (float)Math.toRadians(25.0), 0.0f);
        this.animator.move(this.left_arm2, 0.0f, -2.0f, 2.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(32.5), (float)Math.toRadians(-7.5), (float)Math.toRadians(57.5));
        this.animator.move(this.right_arm, -4.0f, 8.0f, 2.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(-25.0), (float)Math.toRadians(12.5));
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-12.5), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, 8.0f);
        this.animator.move(this.right_leg, 0.0f, 0.0f, -6.0f);
        this.animator.endKeyframe();
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_BLACKHOLE);
        this.animator.startKeyframe(12);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(42.5), 0.0f);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(2.5), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-12.5), (float)Math.toRadians(22.5), (float)Math.toRadians(-10.0));
        this.animator.move(this.right_leg, 0.0f, 0.0f, 9.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-35.0), 0.0f);
        this.animator.move(this.left_leg, 0.0f, -7.0f, -9.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-70.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(55.0));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), 0.0f, (float)Math.toRadians(-57.5));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5), 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(12);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(42.5), 0.0f);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(5.0), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(17.5), (float)Math.toRadians(20.0), (float)Math.toRadians(10.0));
        this.animator.move(this.right_leg, 0.0f, 0.0f, 9.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-30.0), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -9.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(30.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(62.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-32.5), 0.0f, (float)Math.toRadians(-50.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5), 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_ROCKETPUNCH);
        this.animator.startKeyframe(0);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(42.5), 0.0f);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(5.0), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(17.5), (float)Math.toRadians(20.0), (float)Math.toRadians(10.0));
        this.animator.move(this.right_leg, 0.0f, 0.0f, 9.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-30.0), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -9.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(30.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(62.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-32.5), 0.0f, (float)Math.toRadians(-50.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5), 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(42.5), 0.0f);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(10.0), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(17.5), (float)Math.toRadians(25.0), (float)Math.toRadians(10.0));
        this.animator.move(this.right_leg, 0.0f, 0.0f, 13.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-35.0), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -9.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(40.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(62.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-57.5), 0.0f, (float)Math.toRadians(-55.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.right_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5), 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.root, 0.0f, (float)Math.toRadians(-52.5), 0.0f);
        this.animator.rotate(this.lowerbody, 0.0f, (float)Math.toRadians(-20.0), 0.0f);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(12.5), 0.0f, (float)Math.toRadians(-12.5));
        this.animator.move(this.right_leg, 0.0f, 0.0f, 13.0f);
        this.animator.rotate(this.left_leg, 0.0f, (float)Math.toRadians(-35.0), 0.0f);
        this.animator.move(this.left_leg, 0.0f, 0.0f, -9.0f);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-27.5), (float)Math.toRadians(-2.5), (float)Math.toRadians(72.5));
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-10.0), (float)Math.toRadians(-62.5));
        this.animator.move(this.right_arm, -4.0f, 0.0f, 0.0f);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0f, 0.0f);
        this.animator.move(this.left_arm2, 0.0f, 6.0f, 6.0f);
        this.animator.rotate(this.helmet, (float)Math.toRadians(-10.0), (float)Math.toRadians(32.5), 0.0f);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(15);
        this.animator.resetKeyframe(15);
    }

    public void setupAnim(Ender_Guardian_Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.animate(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
        float walkSpeed = 0.5f;
        float walkDegree = 0.5f;
        this.faceTarget(netHeadYaw, headPitch, 1.0f, new AdvancedModelBox[]{this.helmet});
        this.walk(this.left_leg, walkSpeed, walkDegree * 1.2f, true, 0.0f, 0.0f, limbSwing, limbSwingAmount);
        this.flap(this.root, walkSpeed, walkDegree * 0.2f, false, 0.0f, 0.0f, limbSwing, limbSwingAmount);
        this.walk(this.right_leg, walkSpeed, walkDegree * 1.2f, false, 0.0f, 0.0f, limbSwing, limbSwingAmount);
        this.walk(this.left_arm, walkSpeed, walkDegree * 1.2f, false, 0.0f, 0.0f, limbSwing, limbSwingAmount);
        this.walk(this.right_arm, walkSpeed, walkDegree * 1.2f, true, 0.0f, 0.0f, limbSwing, limbSwingAmount);
        this.upperhelmet.showModel = !entityIn.getIsHelmetless();
        this.head.showModel = entityIn.deathTime <= 100;
    }

    public Iterable<AdvancedModelBox> getAllParts() {
        return ImmutableList.of((Object)this.root, (Object)this.left_arm, (Object)this.right_arm, (Object)this.left_arm2, (Object)this.right_arm2, (Object)this.left_fist, (Object)this.right_fist, (Object)this.left_leg, (Object)this.right_leg, (Object)this.head, (Object)this.armor, (Object)this.helmet, (Object[])new AdvancedModelBox[]{this.upperhelmet, this.lowerbody, this.upperbody, this.rightarmor, this.leftarmor});
    }

    public BasicModelPart root() {
        return this.root;
    }

    public void setRotationAngle(AdvancedModelBox AdvancedModelBox2, float x, float y, float z) {
        AdvancedModelBox2.rotateAngleX = x;
        AdvancedModelBox2.rotateAngleY = y;
        AdvancedModelBox2.rotateAngleZ = z;
    }
}

